'use strict';
const fs=require('node:fs'),path=require('node:path'),assert=require('node:assert/strict'),freeze=require('./freeze.json');
const NEW_CASES=['cumulative_diagnostics_count_sum_max_and_failure_are_independent','cumulative_diagnostics_saturate_instead_of_wrapping','cumulative_diagnostics_cancelled_span_is_not_success','cumulative_diagnostics_concurrent_snapshots_keep_counter_invariants','cumulative_diagnostics_payload_is_ids_and_fixed_numeric_counters_only','cumulative_diagnostics_disabled_has_no_state_and_preserves_receipt','cumulative_diagnostics_enabled_preserves_raw_and_unbound_cleanup','cumulative_diagnostics_projection_error_still_fails_complete_and_keeps_raw','cumulative_diagnostics_keeps_admission_backpressure_and_durable_complete_wait','cumulative_diagnostics_cancelling_pending_record_keeps_only_admitted_frames','cumulative_diagnostics_cancelling_complete_does_not_cancel_durable_worker','cumulative_diagnostics_concurrent_complete_waiters_share_one_durable_receipt'];
const EXISTING=['chat_tool_fragments_preserve_numeric_index_order_and_exact_arguments','tiny_fragment_burst_waits_for_slow_archive_and_preserves_every_frame','complete_waits_for_durable_commit','complete_exposes_projection_failure_while_raw_remains_durable','late_binding_during_admitted_frame_drain_preserves_exact_bound_archive','late_binding_replays_all_pages_without_empty_reads_and_still_links_new_nodes','burst_batching_preserves_every_frame_and_avoids_scheduler_sized_parts','large_valid_history_is_complete_beyond_old_aggregate_and_item_limits','classifier_waits_for_sink_instead_of_buffering_all_history_facts','chat_sse_exact_bytes_fragmented_utf8_tool_arguments_schema_and_usage'];
const API_CASES=['client_http_body_tee_preserves_json_and_sse_bytes_and_marks_drop_incomplete','client_http_observer_preserves_trailers_and_size_hint','client_http_pending_drop_uses_protocol_terminal_but_io_errors_remain_incomplete'];
function check(text,expected,cases){
 const totals=[...text.matchAll(/test result: ok\. (\d+) passed; (\d+) failed; (\d+) ignored;/g)];assert.equal(totals.length,1,'one test executable result required');assert.equal(Number(totals[0][1]),expected,'unexpected/zero Rust case count');assert.equal(Number(totals[0][2]),0);assert.equal(Number(totals[0][3]),0);
 for(const name of cases)assert.match(text,new RegExp('test [^\\n]*'+name+' \\.{3} ok'),'missing passing required case '+name);
 assert.equal((text.match(/^test [^\n]* \.\.\. ok$/gm)||[]).length,expected,'per-case success lines required');return{passed:expected,failed:0,ignored:0,required:cases};
}
function main(out){assert.equal(NEW_CASES.length,freeze.functional_gates.new_Rust_cases);const rows=[];for(const mode of [0,1])for(const[kind,n,cases]of [['control-plane',freeze.functional_gates.control_plane_expected_per_mode,[...NEW_CASES,...EXISTING]],['api-observer',freeze.functional_gates.api_server_expected_per_mode,API_CASES]]){const log=kind+'-mode'+mode+'.log';rows.push({log,diagnostics_env:String(mode),...check(fs.readFileSync(path.join(out,log),'utf8'),n,cases)});}assert.equal(rows.reduce((n,row)=>n+row.passed,0),freeze.functional_gates.expected_total_Rust_cases);console.log(JSON.stringify(rows,null,2));}
if(require.main===module)main(process.argv[2]);module.exports={NEW_CASES,EXISTING,API_CASES,check};
