[package]
name = "storage-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
access-control = { path = "../../access-control" }
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
control-plane = { path = "../../control-plane" }
domain = { path = "../../domain" }
futures-util.workspace = true
plugin-framework = { path = "../../plugin-framework" }
runtime-core = { path = "../../runtime-core" }
serde_json.workspace = true
sha2.workspace = true
sqlx.workspace = true
time.workspace = true
tracing.workspace = true
uuid.workspace = true

[dev-dependencies]
postgres-test-support = { path = "../../postgres-test-support" }
tokio.workspace = true
