use super::*;

#[test]
fn ac_002_ac_013_plugins_and_models_owner_routes_have_explicit_assembly_ownership() {
    let assembly = crate::routes::frontend_block_catalog::route_assembly()
        .merge(crate::routes::js_dependencies::route_assembly())
        .merge(crate::routes::model_definitions::route_assembly())
        .merge(crate::routes::model_providers::route_assembly())
        .merge(crate::routes::node_contributions::route_assembly())
        .merge(crate::routes::plugins::route_assembly());

    assert_eq!(
        route_bindings(&assembly),
        vec![
            (
                "GET",
                "/api/console/frontend-blocks",
                "frontend_blocks.view"
            ),
            (
                "GET",
                "/api/console/js-dependencies",
                "js_dependencies.view"
            ),
            (
                "GET",
                "/api/console/models/agent-flow-options",
                "agent_flow.data_model_options.list"
            ),
            (
                "GET",
                "/api/console/model-providers/providers/:provider_code/icon",
                "model_providers.icons.view"
            ),
            (
                "GET",
                "/api/console/model-providers/options",
                "model_providers.options.view"
            ),
            (
                "GET",
                "/api/console/model-providers/:id/balance",
                "model_providers.balance.view"
            ),
            (
                "GET",
                "/api/console/settings/model-providers/catalog",
                "model_providers.catalog.view"
            ),
            (
                "GET",
                "/api/console/settings/model-providers/request-logs",
                "model_providers.request_logs.view"
            ),
            (
                "DELETE",
                "/api/console/settings/model-providers/request-logs",
                "model_providers.request_logs.delete"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/request-logs/clear",
                "model_providers.request_logs.clear"
            ),
            (
                "GET",
                "/api/console/settings/model-providers/instances",
                "model_providers.instances.view"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/instances",
                "model_providers.instances.create"
            ),
            (
                "GET",
                "/api/console/settings/model-providers/providers/:provider_code/main-instance",
                "model_providers.main_instance.view"
            ),
            (
                "PUT",
                "/api/console/settings/model-providers/providers/:provider_code/main-instance",
                "model_providers.main_instance.update"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/preview-models",
                "model_providers.preview.view"
            ),
            (
                "GET",
                "/api/console/settings/model-providers/options",
                "model_providers.settings_options.view"
            ),
            (
                "PATCH",
                "/api/console/settings/model-providers/instances/:id",
                "model_providers.instances.update"
            ),
            (
                "DELETE",
                "/api/console/settings/model-providers/instances/:id",
                "model_providers.instances.delete"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/instances/:id/validate",
                "model_providers.instances.validate"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/instances/:id/secrets/reveal",
                "model_providers.instances.secrets.reveal"
            ),
            (
                "GET",
                "/api/console/settings/model-providers/instances/:id/models",
                "model_providers.instances.models.view"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/instances/:id/models/refresh",
                "model_providers.instances.models.refresh"
            ),
            (
                "GET",
                "/api/console/node-contributions",
                "node_contributions.view"
            ),
            (
                "GET",
                "/api/console/settings/extension-center/installed",
                "extension_center.installed.view"
            ),
            (
                "POST",
                "/api/console/settings/extension-center/installed/:installation_id/select",
                "extension_center.installed.select"
            ),
            (
                "DELETE",
                "/api/console/settings/extension-center/installed/:installation_id",
                "extension_center.installed.delete"
            ),
            (
                "GET",
                "/api/console/settings/extension-center/catalog/:category",
                "extension_center.catalog.view"
            ),
            (
                "GET",
                "/api/console/settings/extension-center/catalog/:category/:catalog_id",
                "extension_center.catalog.detail"
            ),
            (
                "POST",
                "/api/console/settings/extension-center/update-check",
                "extension_center.update_check"
            ),
            (
                "POST",
                "/api/console/settings/extension-center/install",
                "extension_center.install"
            ),
            (
                "POST",
                "/api/console/settings/extension-center/update",
                "extension_center.update"
            ),
            (
                "POST",
                "/api/console/settings/extension-center/install-upload",
                "extension_center.install.upload"
            ),
            (
                "GET",
                "/api/console/plugins/catalog",
                "plugins.catalog.view"
            ),
            (
                "GET",
                "/api/console/plugins/families",
                "plugins.families.view"
            ),
            (
                "POST",
                "/api/console/plugins/families/:provider_code/upgrade-latest",
                "plugins.families.upgrade"
            ),
            (
                "POST",
                "/api/console/plugins/families/:provider_code/switch-version",
                "plugins.families.switch"
            ),
            (
                "DELETE",
                "/api/console/plugins/families/:provider_code",
                "plugins.families.delete"
            ),
            (
                "GET",
                "/api/console/plugins/official-catalog",
                "plugins.official_catalog.view"
            ),
            (
                "POST",
                "/api/console/plugins/install-upload",
                "plugins.install.upload"
            ),
            ("POST", "/api/console/plugins/install", "plugins.install"),
            (
                "POST",
                "/api/console/plugins/install-official",
                "plugins.install.official"
            ),
            (
                "POST",
                "/api/console/plugins/:installation_id/catalog-projection/refresh",
                "plugins.catalog_projection.refresh"
            ),
            (
                "POST",
                "/api/console/plugins/:installation_id/artifact/refresh",
                "plugins.artifact.refresh"
            ),
            (
                "POST",
                "/api/console/plugins/:installation_id/artifact/install-current-node",
                "plugins.artifact.install"
            ),
            (
                "POST",
                "/api/console/plugins/:installation_id/enable",
                "plugins.enable"
            ),
            (
                "POST",
                "/api/console/plugins/:installation_id/assign",
                "plugins.assign"
            ),
            ("GET", "/api/console/plugins/tasks", "plugins.tasks.view"),
            (
                "GET",
                "/api/console/plugins/tasks/:task_id",
                "plugins.tasks.view"
            ),
            (
                "GET",
                "/api/console/settings/model-providers/plugins/families",
                "model_provider_plugins.families.view"
            ),
            (
                "GET",
                "/api/console/settings/model-providers/plugins/official-catalog",
                "model_provider_plugins.official_catalog.view"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/plugins/install-official",
                "model_provider_plugins.install.official"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/plugins/install-upload",
                "model_provider_plugins.install.upload"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/plugins/:installation_id/artifact/refresh",
                "model_provider_plugins.artifact.refresh"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/plugins/:installation_id/artifact/install-current-node",
                "model_provider_plugins.artifact.install"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/plugins/families/:provider_code/upgrade-latest",
                "model_provider_plugins.families.upgrade"
            ),
            (
                "POST",
                "/api/console/settings/model-providers/plugins/families/:provider_code/switch-version",
                "model_provider_plugins.families.switch"
            ),
            (
                "DELETE",
                "/api/console/settings/model-providers/plugins/families/:provider_code",
                "model_provider_plugins.families.delete"
            ),
            (
                "GET",
                "/api/console/settings/model-providers/plugins/tasks/:task_id",
                "model_provider_plugins.tasks.view"
            ),
        ]
    );
}
