'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),cp=require('node:child_process');
const freeze=require('./freeze.json');
const hash=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
function prove({metadata,binaryRecord,proof,provider,apiTree,binaryHash,packages}){
 assert.equal(metadata.id,freeze.reuse_artifact_id);assert.equal(metadata.expired,false);assert.equal(metadata.digest,'sha256:'+freeze.reuse_artifact_sha256);assert.equal(metadata.workflow_run.id,freeze.reuse_run);assert.equal(metadata.workflow_run.head_sha,'e6f04ad83441a0c5b9baa0f03b9eae235b8c9058');
 assert.equal(binaryRecord.source,freeze.product_source);assert.equal(binaryRecord.api_tree,freeze.product_api_tree);assert.equal(apiTree,freeze.product_api_tree);assert.equal(binaryRecord.sha256,freeze.api_binary_sha256);assert.equal(binaryHash,freeze.api_binary_sha256);assert.equal(proof.baseline,freeze.product_source);assert.equal(proof.baseline_binary_sha256,binaryHash);assert.equal(binaryRecord.profile,'release');assert.equal(binaryRecord.features,'default');
 assert.equal(provider.official_source_sha,freeze.provider_source);for(const[name,want]of Object.entries(freeze.provider_packages_sha256)){assert.equal(packages[name],want);assert.equal(provider.providers[name].validated_package_sha256,want);}
 return{status:'pass',product_source:freeze.product_source,api_tree:apiTree,binary_sha256:binaryHash,archive_sha256:freeze.reuse_artifact_sha256,archive_digest_source:'official immutable metadata; binary/package bytes independently hashed',reuse_run:freeze.reuse_run,provider_source:freeze.provider_source};
}
function main(){
 const source='tmp/terminal-aa-reuse',out='tmp/test-governance/gateway-terminal-aa/build',old=path.join(source,'test-governance/gateway-identity-reuse/build');fs.mkdirSync(out,{recursive:true});
 const read=p=>JSON.parse(fs.readFileSync(p));const binary=path.join(old,'baseline-release-api-server');const provider=read(path.join(source,'protocol-reuse/ai-gateway-concurrency/provider-provenance.json'));
 const packages={};for(const[name,want]of Object.entries(freeze.provider_packages_sha256)){const dir=path.join(source,'protocol-reuse/ai-gateway-quality-gate/packages',name);const files=fs.readdirSync(dir).filter(x=>x.endsWith('.1flowbasepkg'));assert.equal(files.length,1);const file=path.join(dir,files[0]);packages[name]=hash(file);assert.equal(packages[name],want);const target=path.join('tmp/protocol-reuse/ai-gateway-quality-gate/packages',name);fs.mkdirSync(target,{recursive:true});fs.copyFileSync(file,path.join(target,files[0]));}
 const receipt=prove({metadata:read(path.join(out,'reuse-artifact-metadata.json')),binaryRecord:read(path.join(old,'binaries.json')).baseline,proof:read(path.join(old,'source-proof.json')),provider,apiTree:cp.execFileSync('git',['rev-parse','HEAD:api'],{encoding:'utf8'}).trim(),binaryHash:hash(binary),packages});
 fs.copyFileSync(binary,path.join(out,'baseline-release-api-server'));fs.chmodSync(path.join(out,'baseline-release-api-server'),0o700);fs.copyFileSync(path.join(old,'toolchain.txt'),path.join(out,'reused-toolchain.txt'));fs.copyFileSync(path.join(old,'gate-counts.json'),path.join(out,'previous-candidate-gate-counts.json'));fs.copyFileSync(path.join(old,'freeze.json'),path.join(out,'previous-run-freeze.json'));
 const provenance='tmp/protocol-reuse/ai-gateway-concurrency';fs.mkdirSync(provenance,{recursive:true});fs.writeFileSync(path.join(provenance,'provider-provenance.json'),JSON.stringify(provider,null,2));fs.writeFileSync(path.join(out,'reuse-provenance.json'),JSON.stringify(receipt,null,2));fs.copyFileSync(path.join(__dirname,'freeze.json'),path.join(out,'freeze.json'));fs.writeFileSync(path.join(out,'harness-sha.txt'),process.env.WORKFLOW_SHA+'\n');console.log('Exact immutable baseline binary/API tree and official packages verified; no Rust build');
}
if(require.main===module)main();module.exports={prove};
