#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process'),readline=require('node:readline');
const {requestSummary,history}=require('../metrics');const {clockIdentity,ns,deltaText,observedHistory,textHash,safeSql,sqlDelta,correlate,loopProbe}=require('../observation');
const ROOT=process.cwd(),OUT=path.join(ROOT,'tmp/test-governance/gateway-terminal-aa');
const{ClientTimeline}=require('./client-timeline'),attemptTiming=require('./attempt-timing');
const freeze=require('./freeze.json'),{diagnosticMetrics}=require('../observer-diagnostic/contract');
const BASELINE=freeze.product_source,CANDIDATE=freeze.product_source,OFFICIAL=freeze.provider_source;
const frozen=x=>require(path.join(ROOT,'scripts/node/ai-gateway-concurrency',x));
const {createGatewayFixture,providerTarget}=frozen('gateway-fixture'),{createDatabase}=frozen('local-acceptance/system'),{singlePackage}=frozen('workflow-contract/inputs'),{responsesEvents}=frozen('mock-upstream/protocol-events');
const {spawnOwned}=frozen('gateway-fixture/process-owner'),{OwnerHttpClient}=frozen('gateway-fixture/http-owner'),{openTemporaryOwnerSession}=require(path.join(ROOT,'scripts/node/page-debug/auth'));
const {redactServiceLog}=frozen('gateway-fixture/service-logs');
const{wholeCounterEvidence}=require('../duplicate-lock/whole-counter');
const{closeOwnedSampler}=require('../lock-scope/sampler-close');
const{createPublishedApplication}=frozen('gateway-fixture/bootstrap');const{validateTargets,semanticDraft,distinctRuns,sqlGuard}=require('../lock-scope/scope-contract');
const delay=ms=>new Promise(r=>setTimeout(r,ms)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const command=(exe,args)=>execFileSync(exe,args,{encoding:'utf8',maxBuffer:1024*1024}).trim();
const ticks=Number(command('getconf',['CLK_TCK']));
fs.mkdirSync(OUT,{recursive:true});
const container=command('docker',['ps','--filter','publish=5432','--format','{{.ID}}']);assert.match(container,/^[a-f0-9]+$/);
const pgPid=Number(command('docker',['inspect','--format','{{.State.Pid}}',container]));
const packageRoot=path.join(ROOT,'tmp/protocol-reuse/ai-gateway-quality-gate/packages');
const packages={openai:singlePackage(path.join(packageRoot,'openai'),'openai'),anthropic:singlePackage(path.join(packageRoot,'anthropic'),'anthropic'),openai_compatible:singlePackage(path.join(packageRoot,'openai_compatible'),'openai_compatible')};
const provenance=require(path.join(ROOT,'tmp/protocol-reuse/ai-gateway-concurrency/provider-provenance.json'));
assert.equal(provenance.official_source_sha,OFFICIAL);
for(const [k,p]of Object.entries(packages))assert.equal(sha(p),provenance.providers[k].validated_package_sha256);
const binaries={baseline:path.join(OUT,'build/baseline-release-api-server')};
const proof=require(path.join(OUT,'build/reuse-provenance.json'));assert.equal(proof.status,'pass');assert.equal(proof.product_source,BASELINE);assert.equal(command('git',['rev-parse','HEAD']),BASELINE);assert.equal(command('git',['rev-parse','HEAD:api']),freeze.product_api_tree);assert.equal(sha(binaries.baseline),freeze.api_binary_sha256);assert.equal(proof.binary_sha256,sha(binaries.baseline));
assert.equal(frozen('workflow-contract/paired-source.lock.json').official_plugins.revision,OFFICIAL);assert.match(fs.readFileSync(require.resolve(path.join(ROOT,'scripts/node/ai-gateway-concurrency/gateway-fixture')),'utf8'),/API_DATABASE_POOL_MAX_CONNECTIONS: '5'/,'Frozen APIpool5 fixture guard');
for(const bin of Object.values(binaries))fs.chmodSync(bin,0o700);
const manifest={product_source:BASELINE,reused_binary:proof,client_clock:clockIdentity(),harness_only:true,harness_sha:process.env.WORKFLOW_SHA,freeze,official:OFFICIAL,profile:'release',features:'default',binary_sha256:Object.fromEntries(Object.entries(binaries).map(([k,p])=>[k,sha(p)])),package_sha256:Object.fromEntries(Object.entries(packages).map(([k,p])=>[k,sha(p)])),clock_ticks:ticks,logical_cpu_count:require('node:os').cpus().length,sample_interval_ms:500,api_pool_max:5,fixture_init_settle_seconds:30,stream:{chunks:256,gap_ms:10,concurrency_levels:[8],history_items:128,text_bytes:524288,rounds:1},sequence:['AA1','AA2'],purpose:'Same60308/same release binary A/A terminal timing diagnosis, not product benefit',warmup:'8sequential full-history warmups per fixture with Native reads, excluded',timing_capture:0,live_lock_watch:false,input_text_sha256:textHash(history(524288)),output_sha256:crypto.createHash('sha256').update('resource-probe-fixed|'.repeat(256)).digest('hex'),limitations:['No unique input correlation; never pair source/client by arrival order.','Native status and5s quiet are not exact protocol/billing/archive flush receipt.','Boundary SQL/network/mock snapshots outside foreground CPU window; whole accounting still includes intermediate observer work; no exact drain flush.']};
fs.writeFileSync(path.join(OUT,'manifest.json'),JSON.stringify(manifest,null,2));
function summarize(samples,ticks,attempted=0){
 const data=diagnosticMetrics(samples,ticks),groups={};
 for(const [name,g]of Object.entries(data.groups))groups[name]={...g,average_cpu_percent_single_core:g.cpu_average_single_core_percent,sampled_peak_cpu_percent_single_core:g.sampled_cpu_peak?.single_core_percent??null,cpu_seconds_per_attempt:g.cpu_seconds===null||!attempted?null:g.cpu_seconds/attempted,rss_sample_peak_bytes:g.rss_peak_bytes,pss_sample_peak_bytes:g.pss_peak_bytes,peak_scope:'sampled interval average; identity gaps retained; ordinary-identity inaccessible PSS/IO remain null'};
 return {...data,groups};
}
function fixedStream(observe=false){const s=responsesEvents('fixed','',''),d=s.chunks[3],text='resource-probe-fixed|',pieces=observe?Array.from({length:256},(_,i)=>deltaText(i,true)):Array(256).fill(text),whole=pieces.join('');s.chunks=[...s.chunks.slice(0,3),...pieces.map(delta=>({...d,delta})),...s.chunks.slice(5)];for(const c of s.chunks){if(c.text!==undefined)c.text=whole;if(c.part?.text!==undefined)c.part.text=whole;if(c.item?.content?.[0])c.item.content[0].text=whole;}s.terminal.response.output[0].content[0].text=whole;s.chunks.forEach((c,i)=>c.sequence_number=i);s.terminal.sequence_number=s.chunks.length;return {events:[...s.chunks,s.terminal],whole};}
function upstream(observe){const {fork}=require('node:child_process');const child=fork(path.join(__dirname,'../mock-server.js'),[],{stdio:['ignore','ignore','pipe','ipc'],env:{...process.env,GATEWAY_PROBE_OBSERVE:observe?'1':'0'}});let n=0,port,readyClock,readyResolve;const forkStart=ns();const pending=new Map();const ready=new Promise(r=>readyResolve=r);child.on('message',m=>{if(m.type==='ready'){port=m.port;readyClock={...m.clock,ready_receive_ns:ns(),fork_start_ns:forkStart};readyResolve();}else if(m.type==='phase'){const p=pending.get(m.id);pending.delete(m.id);if(m.error)p?.reject(Error(m.error));else p?.resolve();}else if(m.type==='stats'){pending.get(m.id)?.(m.value);pending.delete(m.id);}});return {child,ready,clock:()=>readyClock,url:()=>`http://127.0.0.1:${port}`,setPhase:value=>new Promise((resolve,reject)=>{const id=++n;pending.set(id,{resolve,reject});child.send({type:'phase',id,value});}),stats:()=>new Promise(r=>{const id=++n;pending.set(id,r);child.send({type:'stats',id});}),close:()=>new Promise(r=>{if(child.exitCode!==null)return r();child.once('exit',r);child.send({type:'stop'});})};}
function sampler(api,mockPid,out,database,appIds,secrets){const samples=[],pending=new Map();const child=spawn('python3',[path.join(__dirname,'../sampler.py'),String(api),String(pgPid),String(process.pid),String(mockPid)],{stdio:['pipe','pipe','pipe']});const log=fs.createWriteStream(path.join(out,'samples.jsonl'));const closed=new Promise(resolve=>child.once('close',resolve));let errors='';child.stdin.on('error',e=>{errors+='\nstdin: '+e.message;});child.stderr.on('data',c=>{errors=(errors+c).slice(-65536);fs.writeFileSync(path.join(out,'sampler.stderr.log'),redactServiceLog(errors,secrets));});readline.createInterface({input:child.stdout}).on('line',line=>{log.write(line+'\n');const row=JSON.parse(line);samples.push(row);if(row.mark){pending.get(row.mark)?.(row);pending.delete(row.mark);}});return {samples,mark:mark=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('sampler acknowledgement timeout '+errors.slice(-2000))),10000);pending.set(mark,x=>{clearTimeout(timer);resolve(x);});child.stdin.write(JSON.stringify({mark})+'\n');}),close:()=>closeOwnedSampler(child,closed,log,()=>errors.slice(-2000))};}

function dbStats(database){assert.match(database,/^qadb[a-f0-9]+$/);const sql="SELECT json_build_object('database_bytes',pg_database_size(current_database()),'wal_lsn_bytes',pg_wal_lsn_diff(pg_current_wal_lsn(),'0/0'),'sql_calls',(SELECT coalesce(sum(calls),0) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())),'sql_time_ms',(SELECT coalesce(sum(total_exec_time),0) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())),'heap_bytes',(SELECT coalesce(sum(pg_table_size(relid)),0) FROM pg_stat_user_tables),'index_bytes',(SELECT coalesce(sum(pg_indexes_size(relid)),0) FROM pg_stat_user_tables),'inserted_rows',(SELECT coalesce(sum(n_tup_ins),0) FROM pg_stat_user_tables),'updated_rows',(SELECT coalesce(sum(n_tup_upd),0) FROM pg_stat_user_tables),'deleted_rows',(SELECT coalesce(sum(n_tup_del),0) FROM pg_stat_user_tables),'sql_wal_bytes',(SELECT coalesce(sum(wal_bytes),0) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())),'head_tup_upd',(SELECT coalesce(sum(n_tup_upd),0) FROM pg_stat_user_tables WHERE relname='client_trajectory_archive_heads'),'head_tup_hot_upd',(SELECT coalesce(sum(n_tup_hot_upd),0) FROM pg_stat_user_tables WHERE relname='client_trajectory_archive_heads'),'head_tup_ins',(SELECT coalesce(sum(n_tup_ins),0) FROM pg_stat_user_tables WHERE relname='client_trajectory_archive_heads'),'canonical_section_puts',(SELECT count(*) FROM client_trajectory_sections WHERE body_kind='content' AND cardinality(content_path)=0),'client_section_occurrences',(SELECT count(*) FROM client_trajectory_sections),'temp_bytes',(SELECT temp_bytes FROM pg_stat_database WHERE datname=current_database()))";return JSON.parse(command('docker',['exec',container,'psql','-U','postgres','-d',database,'-At','-v','ON_ERROR_STOP=1','-c',sql]));}
function fileLedger(root){const groups={};let stack=[root];while(stack.length){const dir=stack.pop();for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,entry.name);if(entry.isSymbolicLink())continue;if(entry.isDirectory()){stack.push(p);continue;}if(!entry.isFile())continue;const group=path.relative(root,p).split(path.sep)[0],stat=fs.statSync(p);groups[group]??={files:0,logical_bytes:0,allocated_bytes:0};groups[group].files++;groups[group].logical_bytes+=stat.size;groups[group].allocated_bytes+=stat.blocks*512;}}return {groups,total_files:Object.values(groups).reduce((n,x)=>n+x.files,0),total_logical_bytes:Object.values(groups).reduce((n,x)=>n+x.logical_bytes,0),total_allocated_bytes:Object.values(groups).reduce((n,x)=>n+x.allocated_bytes,0),scope:'owned fixture cwd only; external archive roots and compaction backlog not inferred'};}
function pgNetwork(){const line=command('docker',['exec',container,'cat','/proc/net/dev']).split('\n').find(l=>l.trim().startsWith('eth0:'));assert.ok(line);const fields=line.split(':')[1].trim().split(/\s+/).map(Number);return {rx_bytes:fields[0],tx_bytes:fields[8]};}
const diff=(a,b)=>Object.fromEntries(Object.keys(b).map(k=>[k,b[k]-a[k]]));
function eventsCount(raw){return raw.split('\n').filter(l=>l.startsWith('data: ')).reduce((n,l)=>{try{return n+(JSON.parse(l.slice(6)).type==='response.output_text.delta'?1:0);}catch{return n;}},0);}
async function httpCall(url,options={}){
 const timeline=options.stream?new ClientTimeline({expectedDeltas:freeze.fixture.mock_deltas,clock:ns}):null;
 const observation=options.probe_id?{probe_id:options.probe_id,input_text_sha256:textHash(options.body.input),start_ns:ns(),raw_data:[],delta_trace:[]}:null;
 const started=performance.now(),body=options.body?JSON.stringify(options.body):null;
 return new Promise(resolve=>{let finished=false;const finish=value=>{if(!finished){finished=true;if(observation)observation.result_ready_ns=ns();resolve({elapsed_ms:performance.now()-started,...value,...(timeline?{client_timeline:timeline.snapshot()}:{}),...(observation?{observation}: {})});}};
 const req=http.request(url,{method:body?'POST':'GET',agent:false,headers:{...options.headers,...(body?{'content-type':'application/json','content-length':Buffer.byteLength(body)}:{})}},res=>{
  timeline?.headers();const headersMs=performance.now()-started;if(observation)observation.headers_ns=ns();const socket=res.socket,chunks=[];let ttft=null,partial='',lastDelta=null;const deltaGaps=[];
  res.on('data',c=>{const callback=observation?{receive_ns:ns(),bytes:c.length}:null;const callbackIndex=observation?.raw_data.length;if(callback)observation.raw_data.push(callback);try{chunks.push(c);if(options.stream){partial+=c.toString();let nl;while((nl=partial.indexOf('\n'))!==-1){const line=partial.slice(0,nl);partial=partial.slice(nl+1);if(!line.startsWith('data: '))continue;try{const event=JSON.parse(line.slice(6));if(event.type==='response.output_text.delta'){timeline?.delta();const now=performance.now();if(ttft===null)ttft=now-started;if(lastDelta!==null)deltaGaps.push(now-lastDelta);lastDelta=now;if(observation){const match=/^resource-probe-(\d{5})[|]$/.exec(event.delta);observation.delta_trace.push({delta_index:match?Number(match[1]):null,sequence_number:event.sequence_number,raw_callback_index:callbackIndex,parse_ns:ns()});}}if(event.type==='response.created'&&observation)observation.created_response_id=event.response?.id;if(event.type==='response.completed')timeline?.terminal();if(event.type==='response.completed'&&observation)observation.protocol_terminal_ns=ns();}catch{}}}}finally{if(callback)callback.callback_exit_ns=ns();}});
  res.on('error',e=>finish({ok:false,error:e.message}));res.on('end',()=>{timeline?.end();if(observation)observation.end_callback_ns=ns();const raw=Buffer.concat(chunks).toString();let result={headers_ms:headersMs,http:res.statusCode,bytes:Buffer.byteLength(raw),socket_tx_bytes:socket.bytesWritten,socket_rx_bytes:socket.bytesRead,ttft_ms:ttft,interdelta_gap_ms:deltaGaps,ok:res.statusCode===200};
   if(options.stream){const events=raw.split('\n').filter(l=>l.startsWith('data: ')).flatMap(l=>{try{return[JSON.parse(l.slice(6))]}catch{return[]}}),text=events.filter(e=>e.type==='response.output_text.delta').map(e=>e.delta).join('');result.completed=events.filter(e=>e.type==='response.completed').length;result.errors=events.filter(e=>['error','response.failed','response.incomplete','response.cancelled'].includes(e.type)).length;result.output_complete=text===fixedStream(options.output_observe).whole;result.output_sha256=crypto.createHash('sha256').update(text).digest('hex');result.response_id=events.find(e=>e.type==='response.created')?.response?.id;result.delta_count=eventsCount(raw);result.ok&&=result.completed===1&&result.errors===0&&result.output_complete&&ttft!==null&&result.delta_count===256&&timeline.snapshot().valid;
   }else{try{result.body=JSON.parse(raw);}catch{result.ok=false;result.error='non-JSON response';}}if(!result.ok)result.error_body=raw.slice(0,4096);finish(result);
  });
 });req.setTimeout(90000,()=>req.destroy(Error('request timeout90000ms')));req.on('error',e=>finish({ok:false,error:e.message}));req.end(body);});
}
function statementSnapshot(database){const started=performance.now(),start_ns=ns();assert.match(database,/^qadb[a-f0-9]+$/);const sql="SELECT json_build_object('rows',coalesce(json_agg(json_build_object('queryid',queryid::text,'userid',userid::text,'toplevel',toplevel,'query',query,'calls',calls,'total_exec_time',total_exec_time,'rows',rows,'wal_bytes',wal_bytes)),'[]'::json),'info',(SELECT row_to_json(i) FROM pg_stat_statements_info i)) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())";const raw=execFileSync('docker',['exec',container,'psql','-U','postgres','-d',database,'-At','-v','ON_ERROR_STOP=1','-c',sql],{encoding:'utf8',maxBuffer:64*1024*1024});const data=JSON.parse(raw);data.rows=data.rows.map(({query,...row})=>{const normalized_sql=safeSql(query).replace(/\s+/g,' ').trim();return{...row,normalized_sql,query_fingerprint:crypto.createHash('sha256').update(normalized_sql).digest('hex')};});return{...data,start_ns,end_ns:ns(),observation_cost_ms:performance.now()-started,export_bytes:Buffer.byteLength(raw)};}
function nativeStats(database,appIds){assert.ok(appIds.every(x=>/^[a-f0-9-]{36}$/.test(x)));const ids=appIds.map(x=>`'${x}'::uuid`).join(',');const sql=`SELECT json_build_object('manifests',coalesce((SELECT json_agg(r) FROM (SELECT application_id::text, count(*)::bigint AS count, sum(byte_size)::bigint AS byte_size FROM runtime_native_snapshot_manifests WHERE application_id IN (${ids}) GROUP BY application_id) r),'[]'::json),'items',coalesce((SELECT json_agg(r) FROM (SELECT application_id::text,count(*)::bigint AS count,sum(byte_size)::bigint AS byte_size FROM runtime_native_snapshot_items WHERE application_id IN (${ids}) GROUP BY application_id) r),'[]'::json))`;const row=JSON.parse(command('docker',['exec',container,'psql','-U','postgres','-d',database,'-At','-v','ON_ERROR_STOP=1','-c',sql]));for(const group of ['manifests','items'])row[group]=row[group].map(({application_id,...x})=>({...x,app_alias:'app_'+appIds.indexOf(application_id)}));return row;}
function collectAttemptTiming(database,applicationId,runIds){
 const started=performance.now(),start_ns=ns(),cpuBegin=process.cpuUsage();const scope={database,applicationId,runIds};const query=attemptTiming.sql(scope);
 const raw=execFileSync('docker',['exec','-e','PGOPTIONS=-c statement_timeout=3000',container,'psql','-U','postgres','-d',database,'-At','-v','ON_ERROR_STOP=1','-c',query],{encoding:'utf8',maxBuffer:freeze.budget.extra_export_max_bytes,timeout:freeze.budget.extra_command_timeout_ms});
 assert.ok(Buffer.byteLength(raw)<=freeze.budget.extra_export_max_bytes);const data=attemptTiming.rows(JSON.parse(raw),scope);
 return{...data,start_ns,end_ns:ns(),elapsed_ms:performance.now()-started,driver_cpu_us:process.cpuUsage(cpuBegin),export_bytes:Buffer.byteLength(raw),read_only:true,query_count:1,scope:'current owned fixture DB/application/measured run UUIDs only; after whole:end; no full metrics/input/body exported'};
}
async function fixture(label,kind,observe,level){
 const out=path.join(OUT,label);fs.mkdirSync(out,{recursive:true});let f,db,sampling,ownedCwd,loop,ownerClient;
 const mock=upstream(observe),sessions=[],result={label,kind,lane:observe?'observation':'performance',source:kind==='baseline'?BASELINE:CANDIDATE,arm:'same_app',phases:[],cleanup:[],status:'fail',observer_costs:[]},secrets=[];
 const save=()=>fs.writeFileSync(path.join(out,'result.json'),redactServiceLog(JSON.stringify(result,null,2),secrets)+'\n');
 class Client extends OwnerHttpClient{constructor(...args){super(...args);ownerClient=this;}async signIn(account,password){const s=await openTemporaryOwnerSession({apiBaseUrl:this.baseUrl,account,password});sessions.push(s);this.attachSession(s.cookie,s.csrfToken);}}
 try{
  db=createDatabase({container,host:'127.0.0.1',port:5432});secrets.push(db.url,new URL(db.url).password);const database=new URL(db.url).pathname.slice(1);await mock.ready;
  f=await createGatewayFixture({databaseUrl:db.url,apiServerBin:binaries[kind],openaiPackage:packages.openai,anthropicPackage:packages.anthropic,openaiCompatiblePackage:packages.openai_compatible,upstreamBaseUrl:mock.url(),artifactRoot:path.join(out,'service')},{OwnerHttpClient:Client,spawnOwned:(bin,env,options)=>{ownedCwd=options.cwd;return spawnOwned(bin,{...env,FLOWBASE_PROVIDER_STREAM_TIMING_CAPTURE:'0'},options);}});
  const ready=f.result,target=ready.targets.openai,url=ready.gateway_base_url;assert.notEqual(new URL(url).port,'7600');for(const key of ['clock_id','time_namespace','node_version'])assert.equal(clockIdentity()[key],mock.clock()[key],'client/source clock identity '+key);for(const x of Object.values(ready.targets))secrets.push(x.api_key,x.durable.list_runs.headers.cookie);secrets.push(...sessions.map(s=>s.cookie));
  const targets=[target];validateTargets(targets,'same_app');result.target_aliases=['app_0'];
  command('docker',['exec',container,'psql','-U','postgres','-d',database,'-c','CREATE EXTENSION IF NOT EXISTS pg_stat_statements']);result.packages=Object.fromEntries(Object.entries(ready.packages).map(([k,v])=>[k,v.sha256]));result.api_pid=f.gatewayPid;result.pg_pid=pgPid;
  if(observe){const before=BigInt(ns()),python=BigInt(command('python3',['-c','import time;print(time.monotonic_ns())'])),after=BigInt(ns());assert.ok(before<=python&&python<=after);const parent=clockIdentity(),source=mock.clock();for(const key of ['clock_id','time_namespace','node_version'])assert.equal(parent[key],source[key],'Independent mock clock identity '+key);assert.ok(BigInt(source.fork_start_ns)<=BigInt(source.monotonic_ns)&&BigInt(source.monotonic_ns)<=BigInt(source.ready_receive_ns),'Mock READY monotonic bracket');result.clock={...parent,source_receipt:source,max_clock_error_ns:(after-before).toString(),check:'Independent mock READY clock identity/time namespace/Node version; monotonic fork-to-ready bracket; Python CLOCK_MONOTONIC within Node bracket'};}
  await delay(30000);sampling=sampler(f.gatewayPid,mock.child.pid,out,database,targets.map(t=>t.application_id),secrets);const wholeStatementBefore=statementSnapshot(database);const dbBefore=dbStats(database),netBefore=pgNetwork(),mockBefore=await mock.stats();result.files_before=fileLedger(ownedCwd);const wholeBegin=await sampling.mark('whole:begin');if(observe){loop=loopProbe();result.eventloop_probe_interval_ms=loop.interval_ms;}
  async function phase(name,work){
   console.log(JSON.stringify({label,lane:result.lane,phase:name,event:'start',at:new Date().toISOString()}));
   if(observe)await mock.setPhase(name);
   const statementBefore=statementSnapshot(database);if(statementBefore)result.observer_costs.push({phase:name,where:'before',ms:statementBefore.observation_cost_ms,export_bytes:statementBefore.export_bytes});
   const databaseBefore=dbStats(database),networkBefore=pgNetwork(),upstreamBefore=await mock.stats(),begin=await sampling.mark(name+':begin'),record={name,requests:[],observer_enabled:observe};result.phases.push(record);
   const driverCpuBegin=process.cpuUsage();if(observe){record.begin_ns=ns();loop.resume();}
   try{await work(record);}catch(e){record.error=e.message;record.failed=true;}
   if(observe){record.end_work_ns=ns();loop.pause();}
   const end=await sampling.mark(name+':end'),slice=sampling.samples.filter(s=>s.monotonic_ns>=begin.monotonic_ns&&s.monotonic_ns<=end.monotonic_ns);
   record.observer_driver_cpu_us=process.cpuUsage(driverCpuBegin);record.client_clock_reads=record.requests.reduce((n,r)=>n+(r.client_timeline?.clock_reads||0),0);record.client_timeline_json_bytes=record.requests.reduce((n,r)=>n+Buffer.byteLength(JSON.stringify(r.client_timeline||{})),0);record.resources=summarize(slice,ticks,record.requests.length);record.resource_guard={memory_used_peak:Math.max(...slice.map(s=>1-s.memory_available_bytes/s.memory_total_bytes)),disk_used_peak:Math.max(...slice.map(s=>1-s.disk_available_bytes/s.disk_total_bytes)),limit:.9};if(record.resource_guard.memory_used_peak>.9||record.resource_guard.disk_used_peak>.9)record.failed=true;
   record.request_summary=requestSummary(record.requests,record.resources.wall_seconds);record.stream_summary=requestSummary(record.requests.filter(r=>['gateway_stream','direct_stream'].includes(r.request_class)),record.resources.wall_seconds);
   const databaseAfter=dbStats(database);record.database_snapshots={before:databaseBefore,after:databaseAfter};record.database_delta=diff(databaseBefore,databaseAfter);record.head_table_stats={before:databaseBefore.head_tup_upd,after:databaseAfter.head_tup_upd,delta:databaseAfter.head_tup_upd-databaseBefore.head_tup_upd,scope:'per-database relation cumulative stats; sampled after1s quiet, backend flush completeness unverified; not top-level SELECT rows'};record.postgres_network_delta=diff(networkBefore,pgNetwork());const after=await mock.stats();record.upstream_delta=diff(Object.fromEntries(Object.entries(upstreamBefore).filter(([,v])=>typeof v==='number')),Object.fromEntries(Object.entries(after).filter(([,v])=>typeof v==='number')));
   {const statementAfter=statementSnapshot(database);result.observer_costs.push({phase:name,where:'after',ms:statementAfter.observation_cost_ms,export_bytes:statementAfter.export_bytes});record.pg_statement_snapshots={before:statementBefore,after:statementAfter};record.pg_statement_delta=sqlDelta(statementBefore.rows,statementAfter.rows);record.pg_statement_guard=sqlGuard(statementBefore.info,statementAfter.info,record.pg_statement_delta);record.raw_database_delta=record.database_delta;record.database_delta=record.pg_statement_guard.valid?record.raw_database_delta:null;if(!record.pg_statement_guard.valid){record.statement_counter_guard='reset/eviction/missing; SQL completeness unavailable, retain raw CPU/gap';}
    const streams=record.requests.filter(r=>r.observation);if(streams.length){try{record.matched_boundary_observation=correlate(streams,after.request_timeline,name,result.clock);for(const receipt of record.matched_boundary_observation){const client=streams.find(r=>r.observation.probe_id===receipt.probe_id);client.observation_trace=receipt;}}catch(e){record.failed=true;record.correlation_error=e.message;}}
   }
   save();console.log(JSON.stringify({label,phase:name,event:'end',attempted:record.requests.length,failed:record.requests.filter(r=>!r.ok).length,guard_failed:Boolean(record.failed)}));if(record.failed||record.requests.some(r=>!r.ok))throw Error('phase guard '+name);
  }
  await phase('idle',async()=>delay(10000));
  result.native_before_warm=nativeStats(database,targets.map(t=>t.application_id));result.warmups=[];
  for(let i=0;i<8;i++){const t=targets[0];const warm=await httpCall(t.gateway.responses_url,{headers:{authorization:t.gateway.authorization},body:{model:'1flowbase',stream:true,input:history(524288)},stream:true,output_observe:false});assert.ok(warm.ok,'warmup completeness');result.warmups.push({...warm,excluded:true,app_alias:'app_0'});const native=await nativeObservation({...warm,target_index:0});assert.equal(native.native_status,'succeeded','warm native terminal observation');}
  result.native_after_warm=nativeStats(database,targets.map(t=>t.application_id));await delay(30000);const runs=[];
  async function nativeObservation(row){assert.match(row.response_id,/^resp_/);const started=ns(),nativeTarget=targets[row.target_index||0];const native=await httpCall(nativeTarget.durable.query_run.url_template.replace('{run_id}',row.response_id.slice(5)),{headers:nativeTarget.durable.query_run.headers});const data=native.body?.data||native.body;const status=data?.status||data?.run?.status;delete native.body;return{...native,request_class:'native_status',run_id:row.response_id.slice(5),native_status:status,start_ns:started,end_ns:ns(),boundary:'native status observed via query; not exact commit/flush/billing time'};}
  const rounds=1;
  async function batch(mode,record){const rows=await Promise.all(Array.from({length:level},(_,i)=>{const key='scope:h524288:c'+level+':r0:i'+i,input=history(524288),t=targets[0];return httpCall(mode==='gateway'?t.gateway.responses_url:mock.url()+'/v1/responses',{headers:mode==='gateway'?{authorization:t.gateway.authorization}:undefined,body:{model:mode==='gateway'?'1flowbase':t.upstream_model,stream:true,input},stream:true,output_observe:false}).then(x=>({...x,target_index:0,app_alias:'app_0'}));}));record.requests.push(...rows.map(x=>({...x,round:0,request_class:mode==='gateway'?'gateway_stream':'direct_stream'})));if(rows.some(x=>!x.ok))throw Error(mode+' output completeness');if(mode==='gateway'){distinctRuns(rows,level);runs.push(...rows);record.distinct_native_runs=level;}await delay(1000);}
  await phase('direct_before_h524288_c'+level,r=>batch('direct',r));result.native_before_measured=nativeStats(database,targets.map(t=>t.application_id));await phase('fixedstream_h524288_c'+level,r=>batch('gateway',r));result.native_after_measured=nativeStats(database,targets.map(t=>t.application_id));await phase('direct_after_h524288_c'+level,r=>batch('direct',r));
  await phase('drain_observation',async r=>{for(const row of runs){const native=await nativeObservation(row);r.requests.push(native);assert.equal(native.native_status,'succeeded','native durable terminal status; no implicit retry budget');}for(let retry=0;(await mock.stats()).active&&retry<40;retry++)await delay(250);assert.equal((await mock.stats()).active,0);await delay(5000);result.drain={native_runs:runs.length,mock_active:0,quiescence_observation_seconds:5,protocol_flush_receipt:'not exposed/unverified; no total-backlog or storage-saving claim',native_receipt:'status succeeded observed; Native/protocol exact persist and billing times not captured'};});
  const end=await sampling.mark('whole:end');result.total=summarize(sampling.samples.filter(s=>s.monotonic_ns>=wholeBegin.monotonic_ns&&s.monotonic_ns<=end.monotonic_ns),ticks,0);result.total.accounting={scope:'whole fixture including8 sequential warmups, warmup Native queries, warm settle, idle and SQL snapshot export; no per-request denominator',measured_http_requests:result.phases.reduce((n,p)=>n+p.requests.length,0),excluded_warmup_stream_requests:8,excluded_warmup_native_requests:8};const rawWholeDelta=diff(dbBefore,dbStats(database));result.total.raw_database_delta=rawWholeDelta;const wholeStatementAfter=statementSnapshot(database);result.total.pg_statement_snapshots={before:wholeStatementBefore,after:wholeStatementAfter};result.total.whole_counter_evidence=wholeCounterEvidence(wholeStatementBefore,wholeStatementAfter,rawWholeDelta);result.total.database_delta=result.total.whole_counter_evidence.validated_database_delta;result.total.pg_statement_guard=result.total.whole_counter_evidence.guard;if(!result.total.pg_statement_guard.valid)result.total.statement_counter_guard='whole counters incomplete/reset/evicted; raw deltas retained, causal SQL/WAL/storage comparison unavailable';result.files_after=fileLedger(ownedCwd);result.owned_cwd_storage_growth={files:result.files_after.total_files-result.files_before.total_files,logical_bytes:result.files_after.total_logical_bytes-result.files_before.total_logical_bytes,allocated_bytes:result.files_after.total_allocated_bytes-result.files_before.total_allocated_bytes};result.total.postgres_network_delta=diff(netBefore,pgNetwork());const mockAfter=await mock.stats();result.total.upstream_delta=diff(Object.fromEntries(Object.entries(mockBefore).filter(([,v])=>typeof v==='number')),Object.fromEntries(Object.entries(mockAfter).filter(([,v])=>typeof v==='number')));result.actual_mock_interdelta_gap_ms=mockAfter.interdelta_gap_ms;result.mock_request_timeline=mockAfter.request_timeline;assert.ok(mockAfter.request_timeline.every(r=>r.input_items===128&&r.input_text_bytes===524288));result.attempt_timing_collection=collectAttemptTiming(database,targets[0].application_id,runs.map(r=>r.response_id.slice(5)));result.diagnostic_timings_complete=result.attempt_timing_collection.all_summaries_available;assert.ok(result.diagnostic_timings_complete,'required existing provider summaries missing/invalid; no inferred replacement');result.unobserved_server_boundaries=['inner_body_eof','recorder_complete','dispatcher_span'];result.status='pass';
 }catch(e){result.error=redactServiceLog(e.message,secrets);}finally{
  if(loop){loop.stop();result.eventloop_lag=loop.rows;result.eventloop_probe_excluded_intervals=loop.excluded;}if(sampling)try{await sampling.close();}catch(e){result.cleanup.push('sampler-failed');result.sampler_error=redactServiceLog(e.message,secrets);result.error??=result.sampler_error;result.status='fail';}
  for(const s of sessions)try{await s.dispose();result.cleanup.push('session-disposed');}catch{result.status='fail';result.cleanup.push('session-dispose-failed');}
  for(const [name,close]of [['fixture',()=>f?.close()],['mock',()=>mock.close()],['database',()=>db?.close()]])try{await close();result.cleanup.push(name+'-closed');}catch{result.status='fail';result.cleanup.push(name+'-cleanup-failed');}save();
 }
 return result;
}
(async()=>{const results=[];const observe=false;for(const level of [8])for(const [part,kind]of [['AA1','baseline'],['AA2','baseline']]){const label=part;const r=await fixture(label,kind,observe,level);results.push(r);console.log(JSON.stringify({label,status:r.status,error:r.error}));if(r.status!=='pass'){fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify({manifest,results,complete:false},null,2));process.exitCode=1;return;}}fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify({manifest,results,complete:true},null,2));})().catch(e=>{console.error(e.message);process.exitCode=1;});
