'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const freeze=require('./freeze.json'),{verifyFrozenInputs}=require('../observer-diagnostic/contract');
const hash=file=>crypto.createHash('sha256').update(fs.readFileSync(file)).digest('hex');
const root='tmp/diagnostic-reuse',build=root+'/test-governance/gateway-resource-safe/build',out='tmp/test-governance/gateway-api-capability/build';
fs.mkdirSync(out,{recursive:true});
const bins=JSON.parse(fs.readFileSync(build+'/binaries.json'));assert.equal(bins.baseline.source,freeze.product_source);assert.equal(bins.baseline.profile,freeze.profile);assert.equal(bins.baseline.features,freeze.features);assert.equal(bins.baseline.sha256,freeze.baseline_binary_sha256);
const bin=build+'/baseline-release-api-server';assert.equal(hash(bin),freeze.baseline_binary_sha256);fs.copyFileSync(bin,out+'/baseline-release-api-server');
const packages={};for(const [name,expected]of Object.entries(freeze.provider_packages_sha256)){const source=root+'/protocol-reuse/ai-gateway-quality-gate/packages/'+name,files=fs.readdirSync(source).filter(n=>n.endsWith('.1flowbasepkg'));assert.equal(files.length,1);packages[name]=hash(path.join(source,files[0]));assert.equal(packages[name],expected);const target='tmp/protocol-reuse/ai-gateway-quality-gate/packages/'+name;fs.mkdirSync(target,{recursive:true});fs.copyFileSync(path.join(source,files[0]),path.join(target,files[0]));}
const provenanceFile=root+'/protocol-reuse/ai-gateway-concurrency/provider-provenance.json',provenance=JSON.parse(fs.readFileSync(provenanceFile));assert.equal(provenance.official_source_sha,freeze.provider_source);for(const [name,sha]of Object.entries(packages))assert.equal(provenance.providers[name].validated_package_sha256,sha);fs.mkdirSync('tmp/protocol-reuse/ai-gateway-concurrency',{recursive:true});fs.copyFileSync(provenanceFile,'tmp/protocol-reuse/ai-gateway-concurrency/provider-provenance.json');
const git=args=>execFileSync('git',args,{encoding:'utf8'}).trim();const actual={source:git(['rev-parse','HEAD']),apiTree:git(['rev-parse','HEAD:api']),binarySha:hash(out+'/baseline-release-api-server'),packages,profile:bins.baseline.profile,features:bins.baseline.features};verifyFrozenInputs(freeze,actual);assert.equal(git(['status','--porcelain','--untracked-files=no']),'');
const receipt={...actual,harness_sha:process.env.WORKFLOW_SHA,product_tracked_clean:true,product_scope:'explicit prior common baseline, not mutable user dev',binary_reuse_run:36992344470,binary_reuse_artifact:freeze.build_artifact,artifact_sha256:freeze.build_artifact_sha256,toolchain_receipt:fs.readFileSync(build+'/toolchain.txt','utf8'),provider_source:freeze.provider_source,model_calls_real:0};assert.match(receipt.toolchain_receipt,/rustc 1[.]98[.]1/);fs.writeFileSync(out+'/verified-inputs.json',JSON.stringify(receipt,null,2));fs.copyFileSync(path.join(__dirname,'freeze.json'),out+'/freeze.json');console.log(JSON.stringify(receipt));
