'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const{validateTargets,semanticDraft,distinctRuns,sqlGuard,anonymousKey}=require('../scope-contract');const{observedHistory,textHash}=require('../../observation');
test('Eight apps must share provider/model and remain distinct; one shared app is supported',()=>{const ts=Array.from({length:8},(_,i)=>({application_id:String(i),provider_instance_id:'p',model:'m',upstream_model:'u'}));validateTargets(ts,'split_app');validateTargets([ts[0]],'same_app');assert.throws(()=>validateTargets([...ts.slice(0,7),ts[0]],'split_app'));assert.throws(()=>validateTargets(ts.map((x,i)=>({...x,provider_instance_id:String(i)})),'split_app'));});
test('Measured equal-size first-item tags are unique with unchanged remaining127 items',()=>{const a=observedHistory(524288,'scope:r0:i0'),b=observedHistory(524288,'scope:r0:i1');assert.deepEqual(a.slice(1),b.slice(1));assert.notEqual(textHash(a),textHash(b));assert.equal(a.reduce((n,x)=>n+Buffer.byteLength(x.content[0].text),0),524288);assert.deepEqual(a,observedHistory(524288,'scope:r0:i0'));});
test('Semantic draft rejects config drift but ignores only node routing IDs',()=>{const a={graph:{nodes:[{id:'a',type:'start',config:{model:'m'}}]}};assert.equal(semanticDraft(a),semanticDraft({graph:{nodes:[{id:'b',type:'start',config:{model:'m'}}]}}));assert.notEqual(semanticDraft(a),semanticDraft({graph:{nodes:[{id:'b',type:'start',config:{model:'other'}}]}}));});
test('Exact independent successful8 run identities are required',()=>{const rs=Array.from({length:8},(_,i)=>({ok:true,response_id:'resp_'+i}));distinctRuns(rs);assert.throws(()=>distinctRuns(rs.map(r=>({...r,response_id:'resp_same'}))));assert.throws(()=>distinctRuns(rs.map((r,i)=>({...r,ok:i>0}))));});
test('SQL missing/reset/eviction/negative counters invalidate completeness without erasing raw',()=>{const b={stats_reset:'same',dealloc:0},d={rows:[],missing_after_keys:[]};assert.equal(sqlGuard(b,b,d).valid,true);assert.equal(sqlGuard(b,{...b,dealloc:1},d).valid,false);assert.equal(sqlGuard(b,b,{...d,missing_after_keys:['lost']}).valid,false);assert.equal(sqlGuard(b,b,{...d,rows:[{counter_reset_suspected:true}]}).valid,false);});
test('Anonymous keys preserve equality only within same salt and lock domain',()=>{const raw=['advisory','private',123];assert.equal(anonymousKey('synthetic',raw),anonymousKey('synthetic',raw));assert.notEqual(anonymousKey('other',raw),anonymousKey('synthetic',raw));assert.notEqual(anonymousKey('synthetic',['tuple','private',123]),anonymousKey('synthetic',raw));assert.ok(!anonymousKey('synthetic',raw).includes('private'));});

test('Semantic app routing compares edge endpoints and ignores generated edge identifiers',()=>{const d=(a,b,to)=>({graph:{nodes:[{id:a,type:'start',config:{}},{id:b,type:'llm',config:{}}],edges:[{id:'generated-'+a,source:a,target:to||b}]}});assert.equal(semanticDraft(d('a','b')),semanticDraft(d('x','y')));assert.notEqual(semanticDraft(d('a','b')),semanticDraft(d('a','b','a')));});
