'use strict';
const http=require('node:http'),crypto=require('node:crypto');const {responsesEvents}=require(process.cwd()+'/scripts/node/ai-gateway-concurrency/mock-upstream/protocol-events');const delay=ms=>new Promise(r=>setTimeout(r,ms));
function fixedStream(){const s=responsesEvents('fixed','',''),d=s.chunks[3],text='resource-probe-fixed|',whole=text.repeat(256);s.chunks=[...s.chunks.slice(0,3),...Array.from({length:256},()=>({...d,delta:text})),...s.chunks.slice(5)];for(const c of s.chunks){if(c.text!==undefined)c.text=whole;if(c.part?.text!==undefined)c.part.text=whole;if(c.item?.content?.[0])c.item.content[0].text=whole;}s.terminal.response.output[0].content[0].text=whole;s.chunks.forEach((c,i)=>c.sequence_number=i);s.terminal.sequence_number=s.chunks.length;return {events:[...s.chunks,s.terminal],whole};}
function upstream(){let active=0,count=0,input=0,output=0;const sockets=new Set(),gaps=[],requests=[];
 const server=http.createServer(async(req,res)=>{active++;count++;const row={index:count,arrival_ns:process.hrtime.bigint().toString()};requests.push(row);try{const inputChunks=[];for await(const c of req){input+=c.length;inputChunks.push(c);}try{const body=JSON.parse(Buffer.concat(inputChunks));row.input_sha256=crypto.createHash('sha256').update(JSON.stringify(body.input)).digest('hex');}catch{}if(req.method!=='POST'){res.writeHead(404);res.end();return;}res.writeHead(200,{'content-type':'text/event-stream','cache-control':'no-cache'});res.flushHeaders();let previous;for(const event of fixedStream().events){if(event.type==='response.output_text.delta'){if(!row.first_delta_ns)row.first_delta_ns=process.hrtime.bigint().toString();const t=performance.now();if(previous!==undefined)gaps.push(t-previous);previous=t;}const b=`event: ${event.type}\ndata: ${JSON.stringify(event)}\n\n`;output+=Buffer.byteLength(b);if(!res.write(b))await new Promise(r=>res.once('drain',r));await delay(10);}await new Promise(r=>res.end(r));}catch{res.destroy();}finally{row.finished_ns=process.hrtime.bigint().toString();active--;}});
 server.on('connection',s=>sockets.add(s));server.on('upgrade',(_req,s)=>{count++;s.end('HTTP/1.1 426 Upgrade Required\r\nContent-Length: 0\r\nConnection: close\r\n\r\n');});
 return {server,stats:()=>({active,requests:count,body_rx_bytes:input,body_tx_bytes:output,socket_rx_bytes:[...sockets].reduce((n,s)=>n+s.bytesRead,0),socket_tx_bytes:[...sockets].reduce((n,s)=>n+s.bytesWritten,0),interdelta_gap_ms:gaps,request_timeline:requests}),close:async()=>{server.closeAllConnections();await new Promise(r=>server.close(r));}};
}

const mock=upstream();mock.server.listen(0,'127.0.0.1',()=>process.send({type:'ready',port:mock.server.address().port}));process.on('message',async m=>{if(m.type==='stats')process.send({type:'stats',id:m.id,value:mock.stats()});if(m.type==='stop'){await mock.close();process.exit(0);}});
