'use strict';
const crypto=require('node:crypto'),assert=require('node:assert/strict');
const {history}=require('./metrics');
const fs=require('node:fs');
const clockIdentity=()=>({clock_id:'linux-CLOCK_MONOTONIC-boot:'+fs.readFileSync('/proc/sys/kernel/random/boot_id','utf8').trim(),time_namespace:fs.readlinkSync('/proc/self/ns/time'),node_version:process.version,monotonic_ns:ns()});
const ns=()=>process.hrtime.bigint().toString();
function deltaText(index,observe){return observe?`resource-probe-${String(index).padStart(5,'0')}|`:'resource-probe-fixed|';}
function observedHistory(bytes,key){const input=history(bytes),tag=crypto.createHash('sha256').update(key).digest('hex').slice(0,16);const s=input[0].content[0].text;assert.ok(s.length>=20);input[0].content[0].text=s.slice(0,4)+tag+s.slice(20);return input;}
function textHash(input){const texts=input.flatMap(x=>typeof x.content==='string'?[x.content]:(x.content||[]).filter(c=>typeof c.text==='string').map(c=>c.text));return crypto.createHash('sha256').update(JSON.stringify(texts)).digest('hex');}
function safeSql(sql){return sql.replace(/\$([A-Za-z_][A-Za-z_0-9]*)?\$[\s\S]*?\$\1\$/g,'$literal').replace(/(?:[Ee])?'(?:\\.|''|[^'\\])*'/g,'$literal').replace(/--[^\n]*|\/\*[\s\S]*?\*\//g,'$comment');}
function sqlDelta(before,after){const key=r=>[r.userid,r.queryid,r.toplevel].join(':'),old=new Map(before.map(r=>[key(r),r]));const rows=after.map(r=>{const b=old.get(key(r));const delta=Object.fromEntries(['calls','total_exec_time','rows','wal_bytes'].map(k=>[k,r[k]-(b?.[k]||0)]));return{...r,...delta,counter_reset_suspected:Object.values(delta).some(v=>v<0)};});return{rows,top_calls:[...rows].sort((a,b)=>b.calls-a.calls).slice(0,30),top_time:[...rows].sort((a,b)=>b.total_exec_time-a.total_exec_time).slice(0,30),missing_after_keys:before.filter(r=>!after.some(a=>key(a)===key(r))).map(key),sum_delta_by_level:Object.fromEntries([true,false].map(level=>[level?'toplevel':'nested',Object.fromEntries(['calls','total_exec_time','rows','wal_bytes'].map(k=>[k,rows.filter(r=>r.toplevel===level).reduce((n,r)=>n+r[k],0)]))])),accounting:'Do not add nested execution time or WAL to top-level totals'};}
function correlate(clients,source,phase,clock){const ss=source.filter(r=>r.probe_phase===phase);assert.equal(clients.length,ss.length);const hashes=new Set(clients.map(r=>r.observation.input_text_sha256));assert.equal(hashes.size,clients.length,'Diagnostic input hashes must be unique within a phase');return clients.map(c=>{const matches=ss.filter(s=>s.input_text_sha256===c.observation.input_text_sha256);assert.equal(matches.length,1,'Explicit source mapping required');const s=matches[0];assert.equal(c.delta_count,256);assert.equal(s.delta_trace.length,256);const expected=Array.from({length:256},(_,i)=>i);assert.deepEqual(c.observation.delta_trace.map(x=>x.delta_index),expected);assert.deepEqual(s.delta_trace.map(x=>x.delta_index),expected);const monotonic=xs=>xs.every((x,i)=>!i||BigInt(x)>=BigInt(xs[i-1]));assert.ok(monotonic(s.delta_trace.map(x=>x.before_write_ns))&&monotonic(c.observation.delta_trace.map(x=>x.parse_ns)),'Nonmonotonic trace');const send=s.delta_trace.map(x=>x.before_write_ns),receive=c.observation.delta_trace.map(x=>x.parse_ns);for(let i=0;i<256;i++)assert.ok(BigInt(receive[i])+BigInt(clock.max_clock_error_ns)>=BigInt(send[i]),'Receive precedes source beyond clock bound');return{probe_id:c.observation.probe_id,correlation_evidence:'explicit_same_stream_and_delta_sequence',mapping_evidence:'unique same-phase synthetic input text hash plus exact unique output delta indices; no arrival-order inference',clock_id:clock.clock_id,source_clock_id:clock.clock_id,client_clock_id:clock.clock_id,max_clock_error_ns:clock.max_clock_error_ns,delta_sequence:expected,source_send_ns:send,client_receive_ns:receive,source_boundary:'before_res_write',client_boundary:'SSE_delta_parse_callback',source_request_index:s.index};});}
function loopProbe(intervalMs=50){
 const rows=[],excluded=[];const step=BigInt(intervalMs)*1000000n;let timer=null,expected,excludedStart=ns();
 const capture=()=>{const now=process.hrtime.bigint();rows.push({timestamp_ns:now.toString(),lag_ns:(now>expected?now-expected:0n).toString()});expected=now+step;};
 const pause=()=>{if(timer){if(process.hrtime.bigint()>=expected)capture();clearInterval(timer);timer=null;excludedStart=ns();}};
 const resume=()=>{if(timer)return;const now=ns();excluded.push({begin_ns:excludedStart,end_ns:now,reason:'outside stream work; synchronous SQL/resource export excluded'});expected=BigInt(now)+step;timer=setInterval(capture,intervalMs);};
 return{rows,excluded,pause,resume,stop:pause,interval_ms:intervalMs};
}
module.exports={clockIdentity,ns,deltaText,observedHistory,textHash,safeSql,sqlDelta,correlate,loopProbe};
