'use strict';
const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto'),assert=require('node:assert/strict'),{execFileSync}=require('node:child_process');
const RUNTIME='539e335204df667552c56faf4f13b323acb7320b',BASELINE='ed55f8fc73db24beac21ca4831659733ffac3adb',OFFICIAL='997c705b3c564c93d2fc49b973e0b5bbdb759cdc';
const TEST='api/apps/api-server/src/runtime_profile_client/_tests/shared_source_tests.rs';
const HASHES={'test-governance/gateway-monitor-paired/build/baseline-release-api-server':'4993d72c29af1b21a224d2bc5cc15e9cb0721b98b8905dbb6ff4f7d534516f0e','test-governance/gateway-monitor-paired/build/candidate-release-api-server':'07e34e2d6e906bfc2c8fc4ffe5d191353f3f5e276b670eab98c6eba9edcf5630','protocol-reuse/ai-gateway-quality-gate/packages/openai/1flowbase@openai@0.2.69@linux-amd64.1flowbasepkg':'8d5a338447566d8ac26a2572c2d536fad37838e766572df4dd23686965b57b3e','protocol-reuse/ai-gateway-quality-gate/packages/anthropic/1flowbase@anthropic@0.1.44@linux-amd64.1flowbasepkg':'07af38ee7aff8ebd59894f5884a1c5cb7861248a87710e1437d13db429b79642','protocol-reuse/ai-gateway-quality-gate/packages/openai_compatible/1flowbase@openai_compatible@0.3.51@linux-amd64.1flowbasepkg':'33c99266767d7d8cbe8b27c639065d5eeda854453dc8c9cc04c7ac8f64db0516'};
const digest=data=>crypto.createHash('sha256').update(data).digest('hex');
function validateChangedPaths(paths){assert.deepEqual(paths,[TEST],'Release reuse requires exactly the approved test-only change; production changes require a corresponding new build');}
function verifyFiles(root,hashes=HASHES){return Object.fromEntries(Object.entries(hashes).map(([name,expected])=>{const actual=digest(fs.readFileSync(path.join(root,name)));assert.equal(actual,expected,'Artifact hash mismatch: '+name);return[name,actual];}));}
function sourceProof(){const repair=process.env.PAIRED_VALIDATED_TEST_SOURCE;assert.match(repair||'',/^[a-f0-9]{40}$/);const git=args=>execFileSync('git',args,{encoding:'utf8'});assert.equal(git(['rev-parse','HEAD']).trim(),repair);const paths=git(['diff','--name-only','--no-renames','-z',RUNTIME,repair]).split('\0').filter(Boolean);validateChangedPaths(paths);const patch=git(['diff','--no-ext-diff',RUNTIME,repair,'--',TEST]);return{runtime_source:RUNTIME,test_source:repair,baseline:BASELINE,official:OFFICIAL,changed_paths:paths,test_patch_sha256:digest(patch),proof:'Entire tracked repository identical except approved test file; release build inputs unchanged'};}
function main(){const proof=sourceProof(),evidence='tmp/test-governance/gateway-monitor-paired/build';fs.mkdirSync(evidence,{recursive:true});if(!process.argv.includes('--source-only')){proof.artifact_run=36893524316;proof.artifact_id=11181109322;proof.verified_sha256=verifyFiles('tmp');const b=JSON.parse(fs.readFileSync(path.join(evidence,'binaries.json')));assert.equal(b.baseline.source,BASELINE);assert.equal(b.candidate.source,RUNTIME);assert.ok(fs.readFileSync(path.join(evidence,'toolchain.txt'),'utf8').includes('rustc 1.98.1'));const providers=JSON.parse(fs.readFileSync('tmp/protocol-reuse/ai-gateway-concurrency/provider-provenance.json'));assert.equal(providers.official_source_sha,OFFICIAL);proof.binary_manifest=b;}fs.writeFileSync(path.join(evidence,'reuse-proof.json'),JSON.stringify(proof,null,2));console.log(JSON.stringify(proof));}
if(require.main===module)main();
module.exports={validateChangedPaths,verifyFiles,TEST};
