#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process'),readline=require('node:readline');
const {summarize,requestSummary,profileOracle,history}=require('./metrics');
const ROOT=process.cwd(),OUT=path.join(ROOT,'tmp/test-governance/gateway-monitor-paired');
const BASELINE='ed55f8fc73db24beac21ca4831659733ffac3adb',CANDIDATE='539e335204df667552c56faf4f13b323acb7320b',OFFICIAL='997c705b3c564c93d2fc49b973e0b5bbdb759cdc';
const frozen=x=>require(path.join(ROOT,'scripts/node/ai-gateway-concurrency',x));
const {createGatewayFixture}=frozen('gateway-fixture'),{createDatabase}=frozen('local-acceptance/system'),{singlePackage}=frozen('workflow-contract/inputs'),{responsesEvents}=frozen('mock-upstream/protocol-events');
const {spawnOwned}=frozen('gateway-fixture/process-owner'),{OwnerHttpClient}=frozen('gateway-fixture/http-owner'),{openTemporaryOwnerSession}=require(path.join(ROOT,'scripts/node/page-debug/auth'));
const {redactServiceLog}=frozen('gateway-fixture/service-logs');
const delay=ms=>new Promise(r=>setTimeout(r,ms)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const command=(exe,args)=>execFileSync(exe,args,{encoding:'utf8',maxBuffer:1024*1024}).trim();
const ticks=Number(command('getconf',['CLK_TCK']));
fs.mkdirSync(OUT,{recursive:true});
const container=command('docker',['ps','--filter','publish=5432','--format','{{.ID}}']);assert.match(container,/^[a-f0-9]+$/);
const pgPid=Number(command('docker',['inspect','--format','{{.State.Pid}}',container]));
const packageRoot=path.join(ROOT,'tmp/protocol-reuse/ai-gateway-quality-gate/packages');
const packages={openai:singlePackage(path.join(packageRoot,'openai'),'openai'),anthropic:singlePackage(path.join(packageRoot,'anthropic'),'anthropic'),openai_compatible:singlePackage(path.join(packageRoot,'openai_compatible'),'openai_compatible')};
const provenance=require(path.join(ROOT,'tmp/protocol-reuse/ai-gateway-concurrency/provider-provenance.json'));
assert.equal(provenance.official_source_sha,OFFICIAL);
for(const [k,p]of Object.entries(packages))assert.equal(sha(p),provenance.providers[k].validated_package_sha256);
const binaries={baseline:path.join(OUT,'build/baseline-release-api-server'),candidate:path.join(OUT,'build/candidate-release-api-server')};
const builds=require(path.join(OUT,'build/binaries.json'));for(const [k,bin]of Object.entries(binaries))assert.equal(sha(bin),builds[k].sha256);assert.equal(builds.baseline.source,BASELINE);assert.equal(builds.candidate.source,CANDIDATE);
const testSource=process.env.PAIRED_VALIDATED_TEST_SOURCE||CANDIDATE;assert.equal(command('git',['rev-parse','HEAD']),testSource);if(testSource!==CANDIDATE){const proof=require(path.join(OUT,'build/reuse-proof.json'));assert.equal(proof.test_source,testSource);assert.equal(proof.runtime_source,CANDIDATE);assert.equal(proof.binary_manifest.candidate.sha256,builds.candidate.sha256);}
assert.equal(frozen('workflow-contract/paired-source.lock.json').official_plugins.revision,OFFICIAL);
for(const bin of Object.values(binaries))fs.chmodSync(bin,0o700);
const manifest={baseline:BASELINE,candidate:CANDIDATE,test_source:testSource,release_reused_from_run:testSource!==CANDIDATE?36893524316:null,official:OFFICIAL,profile:'release',features:'default',allocator:'same default Cargo feature configuration',rustc:command('rustc',['--version']),binary_sha256:Object.fromEntries(Object.entries(binaries).map(([k,p])=>[k,sha(p)])),package_sha256:Object.fromEntries(Object.entries(packages).map(([k,p])=>[k,sha(p)])),clock_ticks:ticks,logical_cpu_count:require('node:os').cpus().length,sample_interval_ms:500,request_timeout_ms:90000,fixture_init_settle_seconds:30,final_drain_observation_seconds:5,stream:{chunks:256,gap_ms:10,concurrency:[1,8],c1_rounds:6,c8_rounds:2,history_items:128,text_budget_bytes:[8192,524288],warmup:1},monitor:{cycles:4,period_ms:2000},sequence:['A1','B1','B2','A2'],direct_sequence:'direct-before / gateway / direct-after at each concurrency on the same mock/runner',mock_and_client_processes:'separate child mock server and parent client driver',limitations:['Synthetic loopback mock only; no real upstream validation.','No saturation search or capacity conclusion.','Sample peaks are interval averages; short-lived processes may evade samples.','No absolute resource comparison across runs or jobs.','Postgres WAL LSN and container network counters are whole isolated service, SQL calls/database size scoped to temporary DB. SQL counters include bounded diagnostic reads.','All binaries use the539 fixed fixture wrapper; no fixture difference between versions. Dependency differences in Cargo.lock are part of the optimization patch, not normalized away.','Drain waits for upstream handlers and native terminal status, then five-second observation; no generic internal queue-depth API is available.']};
fs.writeFileSync(path.join(OUT,'manifest.json'),JSON.stringify(manifest,null,2));
function fixedStream(){const s=responsesEvents('fixed','',''),d=s.chunks[3],text='resource-probe-fixed|',whole=text.repeat(256);s.chunks=[...s.chunks.slice(0,3),...Array.from({length:256},()=>({...d,delta:text})),...s.chunks.slice(5)];for(const c of s.chunks){if(c.text!==undefined)c.text=whole;if(c.part?.text!==undefined)c.part.text=whole;if(c.item?.content?.[0])c.item.content[0].text=whole;}s.terminal.response.output[0].content[0].text=whole;s.chunks.forEach((c,i)=>c.sequence_number=i);s.terminal.sequence_number=s.chunks.length;return {events:[...s.chunks,s.terminal],whole};}
function upstream(){const {fork}=require('node:child_process');const child=fork(path.join(__dirname,'mock-server.js'),[],{stdio:['ignore','ignore','pipe','ipc']});let n=0,port,readyResolve;const pending=new Map();const ready=new Promise(r=>readyResolve=r);child.on('message',m=>{if(m.type==='ready'){port=m.port;readyResolve();}else if(m.type==='stats'){pending.get(m.id)?.(m.value);pending.delete(m.id);}});return {child,ready,url:()=>`http://127.0.0.1:${port}`,stats:()=>new Promise(r=>{const id=++n;pending.set(id,r);child.send({type:'stats',id});}),close:()=>new Promise(r=>{if(child.exitCode!==null)return r();child.once('exit',r);child.send({type:'stop'});})};}
function sampler(api,mockPid,out){const samples=[],pending=new Map();const child=spawn('sudo',['-n','python3',path.join(__dirname,'sampler.py'),String(api),String(pgPid),String(process.pid),String(mockPid)],{stdio:['pipe','pipe','pipe']});const log=fs.createWriteStream(path.join(out,'samples.jsonl'));let errors='';child.stderr.on('data',c=>errors+=c);readline.createInterface({input:child.stdout}).on('line',line=>{log.write(line+'\n');const row=JSON.parse(line);samples.push(row);if(row.mark){pending.get(row.mark)?.(row);pending.delete(row.mark);}});
 return {samples,mark:mark=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('sampler acknowledgement timeout '+errors.slice(0,200))),10000);pending.set(mark,x=>{clearTimeout(timer);resolve(x);});child.stdin.write(JSON.stringify({mark})+'\n');}),close:async()=>{child.stdin.end(JSON.stringify({stop:true})+'\n');await new Promise((resolve,reject)=>{if(child.exitCode!==null)return child.exitCode===0?resolve():reject(Error('sampler exit '+child.exitCode));child.once('exit',c=>c===0?resolve():reject(Error('sampler exit '+c)));});await new Promise(r=>log.end(r));}};
}
function dbStats(database){assert.match(database,/^qadb[a-f0-9]+$/);const sql="SELECT json_build_object('database_bytes',pg_database_size(current_database()),'wal_lsn_bytes',pg_wal_lsn_diff(pg_current_wal_lsn(),'0/0'),'sql_calls',(SELECT coalesce(sum(calls),0) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())),'sql_time_ms',(SELECT coalesce(sum(total_exec_time),0) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())),'heap_bytes',(SELECT coalesce(sum(pg_table_size(relid)),0) FROM pg_stat_user_tables),'index_bytes',(SELECT coalesce(sum(pg_indexes_size(relid)),0) FROM pg_stat_user_tables),'inserted_rows',(SELECT coalesce(sum(n_tup_ins),0) FROM pg_stat_user_tables),'updated_rows',(SELECT coalesce(sum(n_tup_upd),0) FROM pg_stat_user_tables),'deleted_rows',(SELECT coalesce(sum(n_tup_del),0) FROM pg_stat_user_tables),'sql_wal_bytes',(SELECT coalesce(sum(wal_bytes),0) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())),'temp_bytes',(SELECT temp_bytes FROM pg_stat_database WHERE datname=current_database()))";return JSON.parse(command('docker',['exec',container,'psql','-U','postgres','-d',database,'-At','-v','ON_ERROR_STOP=1','-c',sql]));}
function fileLedger(root){const groups={};let stack=[root];while(stack.length){const dir=stack.pop();for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,entry.name);if(entry.isSymbolicLink())continue;if(entry.isDirectory()){stack.push(p);continue;}if(!entry.isFile())continue;const group=path.relative(root,p).split(path.sep)[0],stat=fs.statSync(p);groups[group]??={files:0,logical_bytes:0,allocated_bytes:0};groups[group].files++;groups[group].logical_bytes+=stat.size;groups[group].allocated_bytes+=stat.blocks*512;}}return {groups,total_files:Object.values(groups).reduce((n,x)=>n+x.files,0),total_logical_bytes:Object.values(groups).reduce((n,x)=>n+x.logical_bytes,0),total_allocated_bytes:Object.values(groups).reduce((n,x)=>n+x.allocated_bytes,0),scope:'owned fixture cwd only; external archive roots and compaction backlog not inferred'};}
function pgNetwork(){const line=command('docker',['exec',container,'cat','/proc/net/dev']).split('\n').find(l=>l.trim().startsWith('eth0:'));assert.ok(line);const fields=line.split(':')[1].trim().split(/\s+/).map(Number);return {rx_bytes:fields[0],tx_bytes:fields[8]};}
const diff=(a,b)=>Object.fromEntries(Object.keys(b).map(k=>[k,b[k]-a[k]]));
function eventsCount(raw){return raw.split('\n').filter(l=>l.startsWith('data: ')).reduce((n,l)=>{try{return n+(JSON.parse(l.slice(6)).type==='response.output_text.delta'?1:0);}catch{return n;}},0);}
async function httpCall(url,options={}){const started=performance.now(),body=options.body?JSON.stringify(options.body):null;return new Promise(resolve=>{let finished=false;const finish=value=>{if(!finished){finished=true;resolve({elapsed_ms:performance.now()-started,...value});}};const req=http.request(url,{method:body?'POST':'GET',agent:false,headers:{...options.headers,...(body?{'content-type':'application/json','content-length':Buffer.byteLength(body)}:{})}},res=>{const headersMs=performance.now()-started;const socket=res.socket,chunks=[];let ttft=null,partial='',lastDelta=null;const deltaGaps=[];res.on('data',c=>{chunks.push(c);if(options.stream){partial+=c.toString();let nl;while((nl=partial.indexOf('\n'))!==-1){const line=partial.slice(0,nl);partial=partial.slice(nl+1);if(!line.startsWith('data: '))continue;try{const event=JSON.parse(line.slice(6));if(event.type==='response.output_text.delta'){const now=performance.now();if(ttft===null)ttft=now-started;if(lastDelta!==null)deltaGaps.push(now-lastDelta);lastDelta=now;}}catch{}}}});res.on('error',e=>finish({ok:false,error:e.message}));res.on('end',()=>{const raw=Buffer.concat(chunks).toString();let result={headers_ms:headersMs,http:res.statusCode,bytes:Buffer.byteLength(raw),socket_tx_bytes:socket.bytesWritten,socket_rx_bytes:socket.bytesRead,ttft_ms:ttft,interdelta_gap_ms:deltaGaps,ok:res.statusCode===200};if(options.stream){const events=raw.split('\n').filter(l=>l.startsWith('data: ')).flatMap(l=>{try{return[JSON.parse(l.slice(6))]}catch{return[]}}),text=events.filter(e=>e.type==='response.output_text.delta').map(e=>e.delta).join('');result.completed=events.filter(e=>e.type==='response.completed').length;result.errors=events.filter(e=>['error','response.failed','response.incomplete','response.cancelled'].includes(e.type)).length;result.output_complete=text===fixedStream().whole;result.output_sha256=crypto.createHash('sha256').update(text).digest('hex');result.response_id=events.find(e=>e.type==='response.created')?.response?.id;result.ok&&=result.completed===1&&result.errors===0&&result.output_complete&&ttft!==null;}else {try{result.body=JSON.parse(raw);}catch{result.ok=false;result.error='non-JSON response';}}if(options.stream){result.delta_count=eventsCount(raw);result.ok&&=eventsCount(raw)===256;}if(!result.ok)result.error_body=raw.slice(0,4096);finish(result);});});req.setTimeout(90000,()=>req.destroy(Error('request timeout 90000ms')));req.on('error',e=>finish({ok:false,error:e.message}));req.end(body);});}
async function fixture(label,kind){const out=path.join(OUT,label);fs.mkdirSync(out,{recursive:true});let f,db,sampling,ownedCwd;const mock=upstream(),sessions=[],result={label,kind,source:kind==='baseline'?BASELINE:CANDIDATE,phases:[],cleanup:[],status:'fail'},secrets=[];const save=()=>fs.writeFileSync(path.join(out,'result.json'),redactServiceLog(JSON.stringify(result,null,2),secrets)+'\n');
 class Client extends OwnerHttpClient{async signIn(account,password){const s=await openTemporaryOwnerSession({apiBaseUrl:this.baseUrl,account,password});sessions.push(s);this.attachSession(s.cookie,s.csrfToken);}}
 try{db=createDatabase({container,host:'127.0.0.1',port:5432});secrets.push(db.url,new URL(db.url).password);const database=new URL(db.url).pathname.slice(1);await mock.ready;f=await createGatewayFixture({databaseUrl:db.url,apiServerBin:binaries[kind],openaiPackage:packages.openai,anthropicPackage:packages.anthropic,openaiCompatiblePackage:packages.openai_compatible,upstreamBaseUrl:mock.url(),artifactRoot:path.join(out,'service')},{OwnerHttpClient:Client,spawnOwned:(bin,env,options)=>{ownedCwd=options.cwd;return spawnOwned(bin,env,options);}});const ready=f.result,target=ready.targets.openai,url=ready.gateway_base_url;assert.notEqual(new URL(url).port,'7600');for(const t of Object.values(ready.targets))secrets.push(t.api_key,t.durable.list_runs.headers.cookie);secrets.push(...sessions.map(s=>s.cookie));
 command('docker',['exec',container,'psql','-U','postgres','-d',database,'-c','CREATE EXTENSION IF NOT EXISTS pg_stat_statements']);
 result.packages=Object.fromEntries(Object.entries(ready.packages).map(([k,v])=>[k,v.sha256]));result.api_pid=f.gatewayPid;result.pg_pid=pgPid;
 await delay(30000);sampling=sampler(f.gatewayPid,mock.child.pid,out);await sampling.mark('whole:begin');const dbBefore=dbStats(database),netBefore=pgNetwork(),mockBefore=await mock.stats();result.files_before=fileLedger(ownedCwd);
 async function phase(name,work){const begin=await sampling.mark(name+':begin'),databaseBefore=dbStats(database),networkBefore=pgNetwork(),upstreamBefore=await mock.stats(),record={name,requests:[]};result.phases.push(record);try{await work(record);}catch(e){record.error=e.message;record.failed=true;}const end=await sampling.mark(name+':end'),slice=sampling.samples.filter(s=>s.monotonic_ns>=begin.monotonic_ns&&s.monotonic_ns<=end.monotonic_ns);record.resources=summarize(slice,ticks,record.requests.length);record.resource_guard={memory_used_peak:Math.max(...slice.map(s=>1-s.memory_available_bytes/s.memory_total_bytes)),disk_used_peak:Math.max(...slice.map(s=>1-s.disk_available_bytes/s.disk_total_bytes)),limit:.9};if(record.resource_guard.memory_used_peak>.9||record.resource_guard.disk_used_peak>.9)record.failed=true;record.request_summary=requestSummary(record.requests,record.resources.wall_seconds);record.stream_summary=requestSummary(record.requests.filter(r=>r.output_complete!==undefined),record.resources.wall_seconds);record.monitor_summary=requestSummary(record.requests.filter(r=>r.output_complete===undefined),record.resources.wall_seconds);record.database_delta=diff(databaseBefore,dbStats(database));record.postgres_network_delta=diff(networkBefore,pgNetwork());const after=await mock.stats();record.upstream_delta=diff(Object.fromEntries(Object.entries(upstreamBefore).filter(([,v])=>typeof v==='number')),Object.fromEntries(Object.entries(after).filter(([,v])=>typeof v==='number')));save();if(record.failed||record.requests.some(r=>!r.ok))throw Error('phase guard '+name);}
 await phase('idle',async()=>delay(10000));
 const profile='/api/console/system/runtime-profile',processes='/api/console/system/runtime-processes';
 async function poll(paths,clients,cycles,record){for(let i=0;i<cycles;i++){const start=performance.now();const rows=await Promise.all(Array.from({length:clients},()=>paths.map(async p=>{const r=await httpCall(url+p,{headers:{cookie:sessions[0].cookie}});const data=r.body?.data;if(p===profile){try{profileOracle(data,i>=1);}catch(e){r.ok=false;r.contract_error=e.message;}}else {const own=data?.processes?.find(p=>p.pid===f.gatewayPid);r.ok&&=Boolean(own?.backend_process&&!own?.terminable&&typeof own?.command==='string'&&own.command.length&&typeof own?.user==='string'&&own.user.length);}
 // Preserve shapes and scalar coverage, not commands, usernames or arbitrary host DTO content.
 r.cpu_availability=p===profile?data?.runtime_targets?.map(t=>({reachable:t.reachable,availability:t.metrics?.cpu?.availability})):undefined;r.contract={own_backend_guard:p===processes?r.ok:undefined,profile_contract_ok:p===profile?r.ok:undefined};delete r.body;return {path:p,cycle:i,...r};})).flat());record.requests.push(...rows);if(i+1<cycles)await delay(Math.max(0,2000-(performance.now()-start)));}}
 for(const [name,paths,clients]of [['profile_only',[profile],1],['process_only',[processes],1],['page_both',[profile,processes],1],['same_cycle_four_clients',[profile,processes],4]])await phase(name,r=>poll(paths,clients,4,r));
 let streamBody={model:'1flowbase',stream:true,input:history(1024)};const runs=[];const warmup=await httpCall(target.gateway.responses_url,{headers:{authorization:target.gateway.authorization},body:streamBody,stream:true});result.warmup={...warmup,excluded_from_measured_phases:true};assert.ok(warmup.ok,'warmup stream completeness');await delay(1000);const sizes=label==='B1'||label==='A2'?[524288,8192]:[8192,524288];for(const bytes of sizes){streamBody={model:'1flowbase',stream:true,input:history(bytes)};
 for(const level of [1,8]){const direct=async(name)=>phase(name,async r=>{for(let round=0;round<(level===1?6:2);round++){const rows=await Promise.all(Array.from({length:level},()=>httpCall(mock.url()+'/v1/responses',{body:{...streamBody,model:target.upstream_model},stream:true})));r.requests.push(...rows.map(x=>({...x,round})));if(rows.some(x=>!x.ok))throw Error('direct completeness guard');await delay(1000);}});await direct('direct_before_h'+bytes+'_c'+level);await phase('fixedstream_h'+bytes+'_c'+level,async r=>{for(let round=0;round<(level===1?6:2);round++){const rows=await Promise.all(Array.from({length:level},()=>httpCall(target.gateway.responses_url,{headers:{authorization:target.gateway.authorization},body:streamBody,stream:true})));r.requests.push(...rows.map(x=>({...x,round})));runs.push(...rows);if(rows.some(x=>!x.ok))throw Error('stream completeness guard');await delay(1000);}});await direct('direct_after_h'+bytes+'_c'+level);}}
 await phase('fixedstream_h512_c8_with_page_poll',async r=>{streamBody={model:'1flowbase',stream:true,input:history(524288)};const [rows]=await Promise.all([Promise.all(Array.from({length:8},()=>httpCall(target.gateway.responses_url,{headers:{authorization:target.gateway.authorization},body:streamBody,stream:true}))),poll([profile,processes],1,2,r)]);r.requests.push(...rows);runs.push(...rows);});
 await phase('drain_observation',async r=>{for(const row of runs){assert.match(row.response_id,/^resp_/);const runId=row.response_id.slice(5);let terminal=false;for(let retry=0;retry<20;retry++){const native=await httpCall(target.durable.query_run.url_template.replace('{run_id}',runId),{headers:target.durable.query_run.headers});const data=native.body?.data||native.body;const status=data?.status||data?.run?.status;delete native.body;r.requests.push({...native,run_id:runId,native_status:status});if(status==='succeeded'){terminal=true;break;}await delay(250);}assert.ok(terminal,'native terminal durable status');}for(let retry=0;(await mock.stats()).active&&retry<40;retry++)await delay(250);assert.equal((await mock.stats()).active,0,'mock backlog drained');await delay(5000);result.drain={native_runs:runs.length,mock_active:(await mock.stats()).active,quiescence_observation_seconds:5,internal_queue_depth:'not exposed; no total-backlog claim'};});
 const end=await sampling.mark('whole:end');result.total=summarize(sampling.samples.filter(s=>s.monotonic_ns<=end.monotonic_ns),ticks,result.phases.reduce((n,p)=>n+p.requests.length,0)+(result.warmup?1:0));result.total.database_delta=diff(dbBefore,dbStats(database));result.files_after=fileLedger(ownedCwd);result.owned_cwd_storage_growth={files:result.files_after.total_files-result.files_before.total_files,logical_bytes:result.files_after.total_logical_bytes-result.files_before.total_logical_bytes,allocated_bytes:result.files_after.total_allocated_bytes-result.files_before.total_allocated_bytes};result.total.postgres_network_delta=diff(netBefore,pgNetwork());const mockAfter=await mock.stats();result.total.upstream_delta=diff(Object.fromEntries(Object.entries(mockBefore).filter(([,v])=>typeof v==='number')),Object.fromEntries(Object.entries(mockAfter).filter(([,v])=>typeof v==='number')));result.actual_mock_interdelta_gap_ms=mockAfter.interdelta_gap_ms;result.input_receipts=mockAfter.request_timeline.map(({index,input_items,input_text_bytes,input_text_sha256,arrival_ns,first_delta_ns,finished_ns})=>({index,input_items,input_text_bytes,input_text_sha256,arrival_ns,first_delta_ns,finished_ns}));assert.ok(result.input_receipts.every(r=>r.input_items===128),'all direct/Gateway upstream128-item history preserved');assert.ok(result.input_receipts.every(r=>[1024,8192,524288].includes(r.input_text_bytes)),'all input text budgets preserved');result.mock_request_timeline=mockAfter.request_timeline;result.status='pass';
 }catch(e){result.error=redactServiceLog(e.message,secrets);}finally{if(sampling)try{await sampling.close();}catch(e){result.cleanup.push('sampler-failed');result.error=e.message;result.status='fail';}for(const s of sessions)try{await s.dispose();result.cleanup.push('session-disposed');}catch{result.status='fail';result.cleanup.push('session-dispose-failed');}for(const [name,close]of [['fixture',()=>f?.close()],['mock',()=>mock.close()],['database',()=>db?.close()]])try{await close();result.cleanup.push(name+'-closed');}catch{result.status='fail';result.cleanup.push(name+'-cleanup-failed');}save();}return result;
}
(async()=>{const results=[];for(const [label,kind]of [['A1','baseline'],['B1','candidate'],['B2','candidate'],['A2','baseline']]){const r=await fixture(label,kind);results.push(r);console.log(JSON.stringify({label,status:r.status,error:r.error}));if(r.status!=='pass')break;}fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify({manifest,results,complete:results.length===4&&results.every(r=>r.status==='pass')},null,2));process.exitCode=results.length===4&&results.every(r=>r.status==='pass')?0:1;})().catch(e=>{console.error(e.message);process.exitCode=1;});
