'use strict';
const fs=require('node:fs'),path=require('node:path'),{spawn,spawnSync}=require('node:child_process');
const {profileGate}=require('./contract');
const wait=ms=>new Promise(r=>setTimeout(r,ms));
function checkedCommand(exe,args,limit=65536){const r=spawnSync(exe,args,{encoding:'utf8',maxBuffer:64*1024*1024});return {status:r.status,error:r.error?.message,output_truncated:(r.stdout?.length||0)>limit,stdout:r.stdout?.slice(0,limit)||'',stderr:r.stderr?.slice(0,65536)||''};}
function inventory(processes){return processes.filter(p=>['api','plugins','postgres'].includes(p.group)).map(p=>{const raw=fs.readFileSync('/proc/'+p.pid+'/stat','utf8'),x=raw.slice(raw.lastIndexOf(')')+2).split(/\s+/);if(Number(x[19])!==p.start_ticks)throw Error('PID identity changed');const maps=fs.readFileSync('/proc/'+p.pid+'/maps','utf8'),status=fs.readFileSync('/proc/'+p.pid+'/status','utf8');const elf=checkedCommand('readelf',['-n','/proc/'+p.pid+'/exe']);return {pid:p.pid,identity:p.identity,ppid:Number(x[1]),group:p.group,maps,status_namespace:status.split('\n').filter(l=>/^(Name|Pid|PPid|NSpid|Uid):/.test(l)).join('\n'),ELF:elf};});}
function facts(){const version=checkedCommand('perf',['--version']);const permissions={};for(const name of ['kernel/perf_event_paranoid','kernel/kptr_restrict','kernel/yama/ptrace_scope']){try{permissions[name]=fs.readFileSync('/proc/sys/'+name,'utf8').trim();}catch(e){permissions[name]={unavailable:e.code};}}return {version,uid:process.getuid(),gid:process.getgid(),permissions,identity:'ordinary current runner process; no privilege changes',mode:'cpu-clock49Hz address-only frame-pointer callchain'};}
function start(out,owned){if(!owned.length||owned.some(p=>!Number.isInteger(p.pid)||p.pid<=1))throw Error('Owned PID list required');fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'ownership-maps.json'),JSON.stringify(owned,null,2));const args=['record','-e','cpu-clock','-F','49','--call-graph','fp','-p',owned.map(x=>x.pid).join(','),'-o',path.join(out,'perf.data')];let stderr='',closedResult;const child=spawn('perf',args,{stdio:['ignore','ignore','pipe']});const closed=new Promise(resolve=>{child.on('error',e=>{closedResult={error:e.message};resolve(closedResult);});child.on('close',(code,signal)=>{closedResult={code,signal};resolve(closedResult);});});child.stderr.on('data',b=>{stderr=(stderr+b).slice(-65536);});return {args,child,ready:async()=>{await wait(250);if(closedResult)throw Error('perf exited before window: '+stderr);},stop:async()=>{if(!closedResult)child.kill('SIGINT');let timerID;const timer=new Promise(resolve=>{timerID=setTimeout(()=>{if(!closedResult)child.kill('SIGKILL');resolve({error:'perf stop timeout'});},5000);});const result=await Promise.race([closed,timer]);clearTimeout(timerID);fs.writeFileSync(path.join(out,'perf.stderr.log'),stderr);fs.writeFileSync(path.join(out,'recorder.json'),JSON.stringify({args,...result,stderr},null,2));return result;}};}
function decode(out){const r=checkedCommand('perf',['script','--ns','-i',path.join(out,'perf.data'),'-F','comm,pid,tid,time,event,ip,sym,dso'],16*1024*1024);fs.writeFileSync(path.join(out,'perf-script.txt'),r.stdout);fs.writeFileSync(path.join(out,'decode.json'),JSON.stringify(r,null,2));const owned=JSON.parse(fs.readFileSync(path.join(out,'ownership-maps.json'))),ids=new Set(owned.map(x=>x.pid));const lines=r.stdout.split('\n').filter(l=>/cpu-clock/.test(l));const parsed=lines.map(l=>{const m=l.match(/^\s*(.*?)\s+(\d+)(?:\/|\s+)(\d+)\s+(\d+[.]\d+):\s+cpu-clock:\s+(?:0x)?([a-f0-9]+)\s+(.+?)\s+\((.*?)\)\s*$/);return m?{comm:m[1],pid:Number(m[2]),tid:Number(m[3]),monotonic_ns:Number(m[4])*1e9,ip:m[5],symbol:m[6],dso:m[7],owned:ids.has(Number(m[2]))}:null;});const known=parsed.filter(x=>x?.owned&&!/unknown|\[unknown\]|^0x/i.test(x.symbol));return {decode_ok:r.status===0&&!r.output_truncated,output_truncated:r.output_truncated,sample_headers:lines.length,parsed_samples:parsed.filter(Boolean).length,known_owned_leaf_samples:known.length,unknown_or_unparsed_samples:lines.length-known.length,samples:parsed,callchain_scope:'FP callchain truncation/unknown retained; leaf supports self on-CPU leads only, no complete-stack assumption',lost_scope:'Inspect original perf.data/recorder stderr for lost/fork/thread coverage; not inferred from a process name'};}
async function capability(out,processes){const f=facts();fs.mkdirSync(out,{recursive:true});fs.writeFileSync(path.join(out,'capability-facts.json'),JSON.stringify(f,null,2));if(f.version.status!==0)return {allowed:false,reason:'existing perf unavailable',facts:f};let rec;try{const own=inventory(processes);fs.writeFileSync(path.join(out,'owned-inventory.json'),JSON.stringify(own,null,2));if(own.some(p=>p.ELF.status!==0))return {allowed:false,reason:'owned ELF/build-ID inaccessible',facts:f};rec=start(out,own);await rec.ready();await wait(1000);await rec.stop();rec=null;const decoded=decode(out);fs.writeFileSync(path.join(out,'sample-audit.json'),JSON.stringify(decoded,null,2));return {allowed:profileGate({tool:f.version.status===0,permission:decoded.decode_ok,symbols:decoded.known_owned_leaf_samples>0,owned:decoded.parsed_samples===decoded.sample_headers&&decoded.samples.filter(Boolean).every(s=>s.owned),mode:'fp'}),reason:decoded.known_owned_leaf_samples?'existing permission and attributable leaf observed':'permission/unwind/leaf attribution insufficient; no fallback',facts:f};}catch(e){return {allowed:false,reason:e.message,facts:f};}finally{if(rec)await rec.stop();}}
module.exports={facts,inventory,start,decode,capability};
