[package]
name = "runtime-extension-host"
version = "0.4.1"
edition.workspace = true
license.workspace = true

[dependencies]
async-trait.workspace = true
libc = "0.2"
jsonschema.workspace = true
http.workspace = true
extension-contracts = { path = "../extension-contracts" }
extension-package-runtime = { path = "../extension-package-runtime" }
runtime-profile = { path = "../runtime-profile" }
runtime-core = { path = "../runtime-core" }
serde.workspace = true
serde_json.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true

[dev-dependencies]
sha2.workspace = true
