mod adapter_descriptor_tests;
mod data_source_contract_tests;
mod lifecycle_contract_tests;
mod plugin_data_model_contract_tests;
mod provider_contract_tests;
mod runtime_target_tests;
mod semantic_terminal_tests;
