mod auth_domain_tests;
mod flow_tests;
mod frontend_component_contract_tests;
mod host_extension_tests;
mod mcp_upstream_tests;
mod modeling_tests;
mod resource_tests;
mod runtime_observability_tests;
mod scope_tests;
