#!/usr/bin/env bash
set -euo pipefail

script_dir=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
config_file=${1:-"$script_dir/resource-limits.conf"}

if [[ ! -r $config_file ]]; then
  printf 'Resource-limit config is not readable: %s\n' "$config_file" >&2
  exit 2
fi

# The profile is a trusted local shell config. Paths are resolved after loading
# it so profile values cannot redirect writes outside the intended locations.
# shellcheck source=/dev/null
source "$config_file"

RUST_CPU_QUOTA=${RUST_CPU_QUOTA:-}
# systemd represents an unlimited CPU quota with an empty assignment.
[[ $RUST_CPU_QUOTA != infinity ]] || RUST_CPU_QUOTA=
RUST_IO_WEIGHT=${RUST_IO_WEIGHT:-100}

profile_mode=${PROFILE_MODE:-}
if [[ $profile_mode != limited && $profile_mode != unlimited ]]; then
  printf 'PROFILE_MODE must be limited or unlimited\n' >&2
  exit 2
fi

user_home=$(getent passwd "$(id -u)" | cut -d: -f6)
systemd_user_dir=${RESOURCE_LIMITS_SYSTEMD_USER_DIR:-"$user_home/.config/systemd/user"}
user_bin_dir=${RESOURCE_LIMITS_USER_BIN_DIR:-"$user_home/.local/bin"}
repo_root=${RESOURCE_LIMITS_REPO_ROOT:-$(cd -- "$script_dir/../.." && pwd)}
systemctl_bin=${RESOURCE_LIMITS_SYSTEMCTL_BIN:-systemctl}
real_cargo=${RESOURCE_LIMITS_REAL_CARGO:-"$user_home/.cargo/bin/cargo"}

session_config="$systemd_user_dir/session.slice.d/50-memory-protection.conf"
app_config="$systemd_user_dir/app.slice.d/50-memory-budget.conf"
dev_config="$systemd_user_dir/dev.slice"
rust_config="$systemd_user_dir/dev-rust.slice"
frontend_config="$systemd_user_dir/dev-frontend.slice"
dev_wrapper="$user_bin_dir/dev-run"
pnpm_wrapper="$user_bin_dir/pnpm"
cargo_wrapper="$user_bin_dir/cargo"
project_config="$repo_root/.1flowbase.verify.local.json"

require_value() {
  local name=$1
  if [[ -z ${!name:-} ]]; then
    printf '%s is required for PROFILE_MODE=limited\n' "$name" >&2
    exit 2
  fi
}

write_limited_profile() {
  local required
  for required in \
    SESSION_MEMORY_LOW \
    APP_OOM_PRESSURE_LIMIT \
    APP_OOM_PRESSURE_DURATION \
    DEV_OOM_PRESSURE_LIMIT \
    DEV_OOM_PRESSURE_DURATION \
    DEV_MEMORY_HIGH \
    DEV_MEMORY_MAX \
    DEV_MEMORY_SWAP_MAX \
    DEV_CPU_QUOTA \
    FRONTEND_MEMORY_HIGH \
    FRONTEND_MEMORY_MAX \
    RUST_MEMORY_HIGH \
    RUST_MEMORY_MAX \
    RUST_MEMORY_SWAP_MAX \
    CARGO_MAX_JOBS \
    PROJECT_CARGO_JOBS \
    PROJECT_CARGO_TEST_THREADS \
    PROJECT_CARGO_INCREMENTAL; do
    require_value "$required"
  done

  if [[ ! $CARGO_MAX_JOBS =~ ^[1-9][0-9]*$ ||
        ! $PROJECT_CARGO_JOBS =~ ^[1-9][0-9]*$ ||
        ! $PROJECT_CARGO_TEST_THREADS =~ ^[1-9][0-9]*$ ||
        ! $PROJECT_CARGO_INCREMENTAL =~ ^(true|false)$ ]]; then
    printf 'Cargo job counts must be positive integers and incremental must be true or false\n' >&2
    exit 2
  fi

  mkdir -p -- "$(dirname -- "$session_config")" "$(dirname -- "$app_config")" \
    "$systemd_user_dir" "$user_bin_dir"

  cat >"$session_config" <<EOF
[Slice]
MemoryAccounting=yes
MemoryLow=$SESSION_MEMORY_LOW
ManagedOOMPreference=avoid
EOF

  cat >"$app_config" <<EOF
[Slice]
MemoryAccounting=yes
ManagedOOMMemoryPressure=kill
ManagedOOMMemoryPressureLimit=$APP_OOM_PRESSURE_LIMIT
ManagedOOMMemoryPressureDurationSec=$APP_OOM_PRESSURE_DURATION
EOF

  cat >"$dev_config" <<EOF
[Unit]
Description=Resource-controlled development workloads

[Slice]
MemoryAccounting=yes
MemoryHigh=$DEV_MEMORY_HIGH
MemoryMax=$DEV_MEMORY_MAX
MemorySwapMax=$DEV_MEMORY_SWAP_MAX
CPUQuota=$DEV_CPU_QUOTA
ManagedOOMMemoryPressure=kill
ManagedOOMMemoryPressureLimit=$DEV_OOM_PRESSURE_LIMIT
ManagedOOMMemoryPressureDurationSec=$DEV_OOM_PRESSURE_DURATION
EOF

  cat >"$rust_config" <<EOF
[Unit]
Description=Memory budget for Rust builds

[Slice]
MemoryAccounting=yes
MemoryHigh=$RUST_MEMORY_HIGH
MemoryMax=$RUST_MEMORY_MAX
MemorySwapMax=$RUST_MEMORY_SWAP_MAX
CPUQuota=$RUST_CPU_QUOTA
IOWeight=$RUST_IO_WEIGHT
EOF

  cat >"$frontend_config" <<EOF
[Slice]
MemoryAccounting=yes
MemoryHigh=$FRONTEND_MEMORY_HIGH
MemoryMax=$FRONTEND_MEMORY_MAX
EOF

  install -m 0755 "$script_dir/resource-dev-run.sh" "$dev_wrapper"
  install -m 0755 "$script_dir/resource-pnpm.sh" "$pnpm_wrapper"

  cat >"$cargo_wrapper" <<EOF
#!/usr/bin/env bash
set -euo pipefail

# Generated by scripts/shell/apply-resource-limits.sh.
readonly real_cargo='$real_cargo'
readonly memory_budget_cargo_jobs=$CARGO_MAX_JOBS

if [[ ! \${CARGO_BUILD_JOBS:-} =~ ^[1-9][0-9]*$ ]] ||
    (( CARGO_BUILD_JOBS > memory_budget_cargo_jobs )); then
  export CARGO_BUILD_JOBS=\$memory_budget_cargo_jobs
fi

capped_cargo_args=()
while (( \$# > 0 )); do
  case \$1 in
    --jobs|-j)
      capped_cargo_args+=("\$1")
      shift
      if (( \$# > 0 )) && [[ \$1 =~ ^[1-9][0-9]*$ ]] &&
          (( \$1 > memory_budget_cargo_jobs )); then
        capped_cargo_args+=("\$memory_budget_cargo_jobs")
      elif (( \$# > 0 )); then
        capped_cargo_args+=("\$1")
      fi
      ;;
    --jobs=[1-9]*|-j[1-9]*)
      job_value=\${1#*=}
      [[ \$1 == -j* ]] && job_value=\${1#-j}
      if [[ \$job_value =~ ^[1-9][0-9]*$ ]] &&
          (( job_value > memory_budget_cargo_jobs )); then
        [[ \$1 == --jobs=* ]] && capped_cargo_args+=("--jobs=\$memory_budget_cargo_jobs")
        [[ \$1 == -j* ]] && capped_cargo_args+=("-j\$memory_budget_cargo_jobs")
      else
        capped_cargo_args+=("\$1")
      fi
      ;;
    *) capped_cargo_args+=("\$1") ;;
  esac
  shift
done
set -- "\${capped_cargo_args[@]}"

if [[ \${CARGO_MEMORY_BUDGET_ACTIVE:-} == 1 ]]; then
  exec "\$real_cargo" "\$@"
fi

if ! systemctl --user is-active default.target >/dev/null 2>&1; then
  printf 'Cargo resource limits unavailable: user systemd manager is not active.\n' >&2
  exit 2
fi

export CARGO_MEMORY_BUDGET_ACTIVE=1
# Keep the wrapper outside the scope so it owns cancellation even when the
# platform launcher moves the compiler into another process group.
readonly cargo_scope="rust-cargo-\$\$-\$RANDOM.scope"
cleanup_cargo_scope() {
  systemctl --user --no-block stop "\$cargo_scope" >/dev/null 2>&1 || true
}
trap 'cleanup_cargo_scope; exit 130' INT
trap 'cleanup_cargo_scope; exit 143' TERM HUP
systemd-run --user --scope --quiet --collect \
  --unit="\$cargo_scope" --property=TimeoutStopSec=2s \
  --slice=dev-rust.slice \
  -- "\$real_cargo" "\$@" <&0 &
cargo_launcher_pid=\$!
set +e
wait "\$cargo_launcher_pid"
cargo_status=\$?
set -e
exit "\$cargo_status"
EOF
  chmod 0755 "$cargo_wrapper"

  cat >"$project_config" <<EOF
{
  "backend": {
    "cargoJobs": $PROJECT_CARGO_JOBS,
    "cargoTestThreads": $PROJECT_CARGO_TEST_THREADS,
    "incremental": $PROJECT_CARGO_INCREMENTAL
  }
}
EOF

  "$systemctl_bin" --user daemon-reload
  "$systemctl_bin" --user set-property --runtime dev.slice \
    "MemoryHigh=$DEV_MEMORY_HIGH" "MemoryMax=$DEV_MEMORY_MAX" \
    "MemorySwapMax=$DEV_MEMORY_SWAP_MAX" "CPUQuota=$DEV_CPU_QUOTA"
  "$systemctl_bin" --user set-property --runtime dev-frontend.slice \
    "MemoryHigh=$FRONTEND_MEMORY_HIGH" "MemoryMax=$FRONTEND_MEMORY_MAX"
  "$systemctl_bin" --user set-property --runtime dev-rust.slice \
    "MemoryHigh=$RUST_MEMORY_HIGH" \
    "MemoryMax=$RUST_MEMORY_MAX" \
    "MemorySwapMax=$RUST_MEMORY_SWAP_MAX" \
    "CPUQuota=$RUST_CPU_QUOTA" \
    "IOWeight=$RUST_IO_WEIGHT"
}

write_unlimited_profile() {
  rm -f -- "$session_config" "$app_config" "$dev_config" "$rust_config" \
    "$cargo_wrapper" "$project_config" "$frontend_config" "$dev_wrapper" "$pnpm_wrapper"
  rmdir --ignore-fail-on-non-empty -- "$(dirname -- "$session_config")" \
    "$(dirname -- "$app_config")" 2>/dev/null || true

  "$systemctl_bin" --user daemon-reload
  local unit
  for unit in dev-rust.slice dev-frontend.slice dev.slice; do
    if "$systemctl_bin" --user is-active --quiet "$unit"; then
      "$systemctl_bin" --user set-property --runtime "$unit" \
        MemoryHigh=infinity MemoryMax=infinity MemorySwapMax=infinity CPUQuota= IOWeight=100
    fi
  done
}

if [[ $profile_mode == limited ]]; then
  write_limited_profile
else
  write_unlimited_profile
fi

printf 'Applied resource profile %s from %s\n' "$profile_mode" "$config_file"
