'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const{ClientTimeline}=require('../client-timeline');
function normal(){let n=0n;const x=new ClientTimeline({clock:()=>{n+=1000000n;return n;}});x.headers();for(let i=0;i<256;i++)x.delta();x.terminal();x.end();return x;}
test('six clock reads, no per-delta timing overhead and terminal differs from body EOF',()=>{const s=normal().snapshot();assert.equal(s.valid,true);assert.equal(s.clock_reads,6);assert.equal(s.delta_events,256);assert.equal(s.first_to_last_delta_ms,1);assert.equal(s.terminal_to_body_end_ms,1);assert.notEqual(s.protocol_completed_ns,s.body_end_ns);assert.ok(!('server_inner_eof_ns' in s));});
test('early EOF does not invent a terminal/last delta',()=>{const x=new ClientTimeline();x.headers();x.delta();x.end();const s=x.snapshot();assert.equal(s.valid,false);assert.ok(s.issues.includes('terminal_count'));assert.equal(s.protocol_completed_ns,undefined);assert.equal(s.last_expected_delta_ns,undefined);});
test('extra delta and duplicated protocol terminal are rejected',()=>{const x=normal();x.delta();x.terminal();const s=x.snapshot();assert.equal(s.valid,false);assert.ok(s.issues.includes('delta_count'));assert.ok(s.issues.includes('terminal_count'));assert.equal(s.clock_reads,6);});
test('out-of-order monotonic timestamps rejected',()=>{const values=[10n,20n,30n,40n,39n,50n];const x=new ClientTimeline({clock:()=>values.shift()});x.headers();for(let i=0;i<256;i++)x.delta();x.terminal();x.end();assert.ok(x.snapshot().issues.includes('monotonic_order'));});
test('same callback timestamps may be equal but not inferred as server flush',()=>{const x=new ClientTimeline({clock:()=>0n});x.headers();for(let i=0;i<256;i++)x.delta();x.terminal();x.end();assert.equal(x.snapshot().valid,true);assert.equal(x.snapshot().terminal_to_body_end_ms,0);assert.match(x.snapshot().boundary,/not server inner EOF/);});
test('tied clock cannot hide terminal before final delta',()=>{const x=new ClientTimeline({clock:()=>0n});x.headers();x.delta();x.terminal();for(let i=1;i<256;i++)x.delta();x.end();assert.equal(x.snapshot().valid,false);assert.ok(x.snapshot().issues.includes('event_order'));assert.equal(x.snapshot().clock_reads,6);});
test('tied clock cannot hide headers after first delta',()=>{const x=new ClientTimeline({clock:()=>0n});x.delta();x.headers();for(let i=1;i<256;i++)x.delta();x.terminal();x.end();assert.equal(x.snapshot().valid,false);assert.ok(x.snapshot().issues.includes('event_order'));assert.equal(x.snapshot().clock_reads,6);});
