'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {Collector,STAGES,validatePayload}=require('../collector');
const ID='11111111-1111-4111-8111-111111111111',FLOW='22222222-2222-4222-8222-222222222222';
function payload(event='complete_end',capture=ID,flow=FLOW){return{version:1,event,capture_id:capture,flow_run_id:flow,ok:true,clock_reads:28,stages:Object.fromEntries(STAGES.map(name=>[name,{count:1,total_ns:10,max_ns:10,failures:0,cancelled:0}]))};}
test('collector accepts fixed numeric counters and no content',()=>{const p=payload();assert.deepEqual(validatePayload(p),p);});
test('collector refuses extra body, secret or nested fields',()=>{for(const key of ['body','input','token','headers','metrics_payload'])assert.throws(()=>validatePayload({...payload(),[key]:'secret'}));const p=payload();p.stages.fact_append.sql='select secret';assert.throws(()=>validatePayload(p));});
test('collector rejects malformed IDs events outcomes and inconsistent metrics',()=>{for(const change of [{capture_id:'not-uuid'},{event:'delta'},{ok:1},{clock_reads:-1},{version:2}])assert.throws(()=>validatePayload({...payload(),...change}));const p=payload();p.stages.archive_commit.max_ns=11;assert.throws(()=>validatePayload(p));});
test('collector parses split and ANSI tracing lines without keeping unrelated logs',()=>{const c=new Collector();const line='\u001b[32mINFO\u001b[0m gateway capture cumulative timing diagnostic='+JSON.stringify(payload())+'\n';c.feed(Buffer.from('ordinary secret log\n'+line.slice(0,70)));c.feed(Buffer.from(line.slice(70)));c.feed(Buffer.from('INFO diagnostic='+JSON.stringify(payload('worker_end'))+' gateway capture cumulative timing\n'));const r=c.select([FLOW],true);assert.equal(r.rows.length,1);assert.equal(r.rows[0].capture_id,ID);assert.equal(r.exported_events,2);assert.equal(r.unrelated_lines,1);assert.doesNotMatch(JSON.stringify(r),/ordinary secret/);});
test('collector only exports exact measured run IDs and rejects missing or duplicate terminal facts',()=>{const c=new Collector();for(const p of [payload('worker_end'),payload(),payload('worker_end','33333333-3333-4333-8333-333333333333','44444444-4444-4444-8444-444444444444')])c.feed(Buffer.from('INFO diagnostic='+JSON.stringify(p)+' gateway capture cumulative timing\n'));assert.equal(c.select([FLOW],true).rows.length,1);assert.throws(()=>c.select(['44444444-4444-4444-8444-444444444444'],true));assert.throws(()=>c.select([FLOW,FLOW],true));c.feed(Buffer.from('INFO diagnostic='+JSON.stringify(payload())+' gateway capture cumulative timing\n'));assert.throws(()=>c.select([FLOW],true));});
test('OFF requires absence of diagnostic records',()=>{const c=new Collector();assert.deepEqual(c.select([FLOW],false).rows,[]);c.feed(Buffer.from('INFO diagnostic='+JSON.stringify(payload())+' gateway capture cumulative timing\n'));assert.throws(()=>c.select([FLOW],false));});
test('bounded diagnostic collector fails closed on overflowing records or malformed matching JSON',()=>{const c=new Collector({eventLimit:1});const line='INFO diagnostic='+JSON.stringify(payload())+' gateway capture cumulative timing\n';c.feed(Buffer.from(line+line));assert.throws(()=>c.select([FLOW],true));const bad=new Collector();bad.feed(Buffer.from('INFO diagnostic={nope} gateway capture cumulative timing\n'));assert.throws(()=>bad.select([FLOW],true));});
test('stdout and stderr partial lines cannot corrupt each other',()=>{const c=new Collector();const line='INFO diagnostic='+JSON.stringify(payload())+' gateway capture cumulative timing\n';c.feed(Buffer.from(line.slice(0,20)),'stdout');c.feed(Buffer.from('unrelated stderr\n'),'stderr');c.feed(Buffer.from(line.slice(20)),'stdout');c.feed(Buffer.from('INFO diagnostic='+JSON.stringify(payload('worker_end'))+' gateway capture cumulative timing\n'),'stdout');assert.equal(c.select([FLOW],true).rows.length,1);});
test('reversed event order and repeated complete waiter counters remain valid snapshots',()=>{const c=new Collector();const complete=payload(),worker=payload('worker_end');worker.stages.complete_wait={count:0,total_ns:0,max_ns:0,failures:0,cancelled:0};complete.stages.complete_wait.count=2;for(const p of [complete,worker])c.feed(Buffer.from('INFO diagnostic='+JSON.stringify(p)+' gateway capture cumulative timing\n'));assert.equal(c.select([FLOW],true).rows[0].worker.stages.complete_wait.count,0);});
