mod host_extension_boot_tests;
mod host_extension_console_plan_tests;
mod host_extension_loader_tests;
mod host_extensions_builtin_tests;
mod host_route_registry_tests;
mod host_worker_registry_tests;
mod official_mcp_bundle_library_tests;
mod official_plugin_registry_tests;
