[package]
name = "storage-durable-postgres"
version.workspace = true
edition.workspace = true
license.workspace = true

[dependencies]
anyhow.workspace = true
async-trait.workspace = true
base64.workspace = true
chacha20poly1305.workspace = true
control-plane = { path = "../../../control-plane" }
control-plane-contracts = { path = "../../../control-plane-contracts" }
domain = { path = "../../../domain" }
futures-util.workspace = true
plugin-framework = { path = "../../../plugin-framework" }
percent-encoding.workspace = true
rand.workspace = true
rand_regex.workspace = true
regex-syntax.workspace = true
storage-durable = { path = "../core" }
serde_json.workspace = true
rust_decimal.workspace = true
sha2.workspace = true
sqlx.workspace = true
thiserror.workspace = true
time.workspace = true
tokio.workspace = true
tracing.workspace = true
url.workspace = true
uuid.workspace = true

[dev-dependencies]
postgres-test-support = { path = "../../../postgres-test-support" }
