'use strict';
const test=require('node:test'),assert=require('node:assert/strict');
const {inventory,perfArgs}=require('../gate');
function fake(){const paths=[];return {paths,read(file){paths.push(file);if(file.endsWith('/stat'))return '123 (owned api) S '+['1',...Array(17).fill('0'),'777'].join(' ');if(file.endsWith('/status'))return 'Pid:\t123\nUid:\t1001\t1001\t1001\t1001\n';if(file.endsWith('/maps'))return 'sealed api mappings';throw Error('unexpected path');},list(){return ['123','124'];},uid:1001};}
test('API only inventory and stable PID, parent and UID',()=>{const io=fake(),row=inventory({pid:123,parent:1,start_ticks:777},io);assert.equal(row.pid,123);assert.equal(row.start_ticks,777);assert.deepEqual(row.thread_ids,[123,124]);assert.ok(io.paths.every(p=>p.startsWith('/proc/123/')));});
test('first denied API file stops without alternate path or later read',()=>{const io=fake();io.read=file=>{io.paths.push(file);throw Object.assign(Error('denied'),{code:'EACCES'});};assert.throws(()=>inventory({pid:123,parent:1},io),{code:'EACCES'});assert.deepEqual(io.paths,['/proc/123/stat']);});
test('PID reuse and foreign UID are rejected',()=>{assert.throws(()=>inventory({pid:123,parent:1,start_ticks:778},fake()),/identity/);const io=fake();io.uid=1002;assert.throws(()=>inventory({pid:123,parent:1},io),/UID/);});
test('single API target fixed mode no inheritance or systemwide profiling',()=>{assert.deepEqual(perfArgs(123,'x'),['record','-e','cpu-clock','-F','49','--call-graph','fp','-p','123','--no-inherit','-o','x']);assert.throws(()=>perfArgs(0,'x'));});
const fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{capability}=require('../gate');
async function withOut(fn){const out=fs.mkdtempSync(path.join(os.tmpdir(),'pure-api-gate-'));try{await fn(out);}finally{fs.rmSync(out,{recursive:true,force:true});}}
test('capability denies before any perf operation and preserves negative evidence',()=>withOut(async out=>{let calls=0;const r=await capability(out,{pid:123},'sealed',{inventory(){throw Object.assign(Error('maps denied'),{code:'EACCES',path:'/proc/123/maps'});},facts(){calls++;}});assert.equal(calls,0);assert.equal(r.perf_record,'not_attempted');assert.equal(r.error_code,'EACCES');assert.equal(r.allowed,false);assert.equal(r.warm_requests,0);}));
function deps(recorded,decoded){return {inventory:()=>({pid:123,thread_ids:[123],group:'api'}),spawnSync:()=>({status:0,stdout:'Build ID: sealed'}),facts:()=>({version:{status:0}}),record:async()=>recorded,decode:()=>decoded};}
test('actual perf denial stops decode, no fallback, preserves recorder error',()=>withOut(async out=>{const d=deps({code:255,stderr:'perf_event_open Operation not permitted'},null);d.decode=()=>{throw Error('decode must not run');};const r=await capability(out,{pid:123},'sealed',d);assert.equal(r.perf_record,'failed');assert.equal(r.allowed,false);assert.match(r.recorder.stderr,/not permitted/);}));
test('empty idle samples prove recorder permission only, never symbolize or trigger load',()=>withOut(async out=>{const r=await capability(out,{pid:123},'sealed',deps({code:0},{decode_ok:true,known_owned_leaf_samples:0,parsed_samples:0,sample_headers:0,samples:[]}));assert.equal(r.perf_record,'permission_pass');assert.equal(r.allowed,false);assert.equal(r.measured_requests,0);assert.match(r.reason,/idle symbol attribution insufficient/);}));
