pub mod application_management;
pub mod auth_center;
pub mod data_models;
pub mod docs;
pub mod file_storages;
pub mod file_tables;
pub mod host_infrastructure;
pub mod i18n_catalog;
pub mod mcp_management;
pub mod members;
pub mod navigation;
pub mod permissions;
mod release_status;
pub mod roles;
pub mod system;
pub mod workspace;
pub mod workspaces;
