#!/usr/bin/env node
'use strict';
const fs=require('node:fs'),path=require('node:path'),http=require('node:http'),assert=require('node:assert/strict'),crypto=require('node:crypto');
const {spawn,execFileSync}=require('node:child_process'),readline=require('node:readline');
const {summarize,requestSummary,history}=require('../metrics');const {clockIdentity,ns,deltaText,observedHistory,textHash,safeSql,sqlDelta,correlate,loopProbe}=require('../observation');
const ROOT=process.cwd(),OUT=path.join(ROOT,'tmp/test-governance/gateway-app-lock-scope');
const BASELINE='80b4e635e1738e1e2df1a22f94dfd7a6bc9a31af',CANDIDATE='80b4e635e1738e1e2df1a22f94dfd7a6bc9a31af',OFFICIAL='997c705b3c564c93d2fc49b973e0b5bbdb759cdc';
const frozen=x=>require(path.join(ROOT,'scripts/node/ai-gateway-concurrency',x));
const {createGatewayFixture,providerTarget}=frozen('gateway-fixture'),{createDatabase}=frozen('local-acceptance/system'),{singlePackage}=frozen('workflow-contract/inputs'),{responsesEvents}=frozen('mock-upstream/protocol-events');
const {spawnOwned}=frozen('gateway-fixture/process-owner'),{OwnerHttpClient}=frozen('gateway-fixture/http-owner'),{openTemporaryOwnerSession}=require(path.join(ROOT,'scripts/node/page-debug/auth'));
const {redactServiceLog}=frozen('gateway-fixture/service-logs');
const{createPublishedApplication}=frozen('gateway-fixture/bootstrap');const{validateTargets,semanticDraft,distinctRuns,sqlGuard}=require('./scope-contract');
const delay=ms=>new Promise(r=>setTimeout(r,ms)),sha=p=>crypto.createHash('sha256').update(fs.readFileSync(p)).digest('hex');
const command=(exe,args)=>execFileSync(exe,args,{encoding:'utf8',maxBuffer:1024*1024}).trim();
const ticks=Number(command('getconf',['CLK_TCK']));
fs.mkdirSync(OUT,{recursive:true});
const container=command('docker',['ps','--filter','publish=5432','--format','{{.ID}}']);assert.match(container,/^[a-f0-9]+$/);
const pgPid=Number(command('docker',['inspect','--format','{{.State.Pid}}',container]));
const packageRoot=path.join(ROOT,'tmp/protocol-reuse/ai-gateway-quality-gate/packages');
const packages={openai:singlePackage(path.join(packageRoot,'openai'),'openai'),anthropic:singlePackage(path.join(packageRoot,'anthropic'),'anthropic'),openai_compatible:singlePackage(path.join(packageRoot,'openai_compatible'),'openai_compatible')};
const provenance=require(path.join(ROOT,'tmp/protocol-reuse/ai-gateway-concurrency/provider-provenance.json'));
assert.equal(provenance.official_source_sha,OFFICIAL);
for(const [k,p]of Object.entries(packages))assert.equal(sha(p),provenance.providers[k].validated_package_sha256);
const binaries={baseline:path.join(OUT,'build/80b-api-server'),candidate:path.join(OUT,'build/80b-api-server')};
const proof=require(path.join(OUT,'build/scope-proof.json'));assert.equal(proof.source,BASELINE);assert.equal(proof.binary_sha256,sha(binaries.baseline));assert.equal(command('git',['rev-parse','HEAD']),BASELINE);
assert.equal(frozen('workflow-contract/paired-source.lock.json').official_plugins.revision,OFFICIAL);assert.match(fs.readFileSync(require.resolve(path.join(ROOT,'scripts/node/ai-gateway-concurrency/gateway-fixture')),'utf8'),/API_DATABASE_POOL_MAX_CONNECTIONS: '5'/,'Frozen APIpool5 fixture guard');
for(const bin of Object.values(binaries))fs.chmodSync(bin,0o700);
const manifest={source:BASELINE,compiled_from:'539e335204df667552c56faf4f13b323acb7320b',official:OFFICIAL,profile:'release',features:'default',binary_sha256:sha(binaries.baseline),package_sha256:Object.fromEntries(Object.entries(packages).map(([k,p])=>[k,sha(p)])),clock_ticks:ticks,logical_cpu_count:require('node:os').cpus().length,sample_interval_ms:500,lock_interval_ms:200,api_pool_max:5,fixture_init_settle_seconds:30,stream:{chunks:256,gap_ms:10,concurrency:8,history_items:128,text_bytes:524288,rounds:1},sequence:['A1','B1','B2','A2'],arms:{baseline:'same_app',candidate:'split_app'},purpose:'diagnostic app-scope intervention, not7f/9d comparison or saturation',warmup:'8sequential full-history warmups per fixture: same app8times or8apps once each; excluded',limitations:['Unique measured first-item tags change owner identity in both arms; inspect actual dedup/write work.','No exact attempt/socket-ready/billing/protocol flush proof.','Latency/aggregate SQL alone do not prove app lock causality; PG observer costs same both arms and recorded.']};
fs.writeFileSync(path.join(OUT,'manifest.json'),JSON.stringify(manifest,null,2));
function fixedStream(observe=false){const s=responsesEvents('fixed','',''),d=s.chunks[3],text='resource-probe-fixed|',pieces=observe?Array.from({length:256},(_,i)=>deltaText(i,true)):Array(256).fill(text),whole=pieces.join('');s.chunks=[...s.chunks.slice(0,3),...pieces.map(delta=>({...d,delta})),...s.chunks.slice(5)];for(const c of s.chunks){if(c.text!==undefined)c.text=whole;if(c.part?.text!==undefined)c.part.text=whole;if(c.item?.content?.[0])c.item.content[0].text=whole;}s.terminal.response.output[0].content[0].text=whole;s.chunks.forEach((c,i)=>c.sequence_number=i);s.terminal.sequence_number=s.chunks.length;return {events:[...s.chunks,s.terminal],whole};}
function upstream(observe){const {fork}=require('node:child_process');const child=fork(path.join(__dirname,'../mock-server.js'),[],{stdio:['ignore','ignore','pipe','ipc'],env:{...process.env,GATEWAY_PROBE_OBSERVE:observe?'1':'0'}});let n=0,port,readyClock,readyResolve;const forkStart=ns();const pending=new Map();const ready=new Promise(r=>readyResolve=r);child.on('message',m=>{if(m.type==='ready'){port=m.port;readyClock={...m.clock,ready_receive_ns:ns(),fork_start_ns:forkStart};readyResolve();}else if(m.type==='phase'){const p=pending.get(m.id);pending.delete(m.id);if(m.error)p?.reject(Error(m.error));else p?.resolve();}else if(m.type==='stats'){pending.get(m.id)?.(m.value);pending.delete(m.id);}});return {child,ready,clock:()=>readyClock,url:()=>`http://127.0.0.1:${port}`,setPhase:value=>new Promise((resolve,reject)=>{const id=++n;pending.set(id,{resolve,reject});child.send({type:'phase',id,value});}),stats:()=>new Promise(r=>{const id=++n;pending.set(id,r);child.send({type:'stats',id});}),close:()=>new Promise(r=>{if(child.exitCode!==null)return r();child.once('exit',r);child.send({type:'stop'});})};}
function sampler(api,mockPid,out,database,appIds,secrets){const samples=[],lockSamples=[],lockErrors=[],pending=new Map();let lockSummary;const child=spawn('sudo',['-n','python3',path.join(__dirname,'sampler.py'),String(api),String(pgPid),String(process.pid),String(mockPid),container,database,JSON.stringify(appIds)],{stdio:['pipe','pipe','pipe']});const log=fs.createWriteStream(path.join(out,'samples.jsonl'));let errors='';child.stderr.on('data',c=>{errors=(errors+c).slice(-65536);fs.writeFileSync(path.join(out,'sampler.stderr.log'),redactServiceLog(errors,secrets));});readline.createInterface({input:child.stdout}).on('line',line=>{log.write(line+'\n');const row=JSON.parse(line);if(row.type==='lock_observation'){lockSamples.push(row);return;}if(row.type==='lock_observer_error'){lockErrors.push(row);return;}if(row.type==='lock_observer_summary'){lockSummary=row;return;}samples.push(row);if(row.mark){pending.get(row.mark)?.(row);pending.delete(row.mark);}});
 return {samples,lockSamples,lockErrors,summary:()=>lockSummary,mark:mark=>new Promise((resolve,reject)=>{const timer=setTimeout(()=>reject(Error('sampler acknowledgement timeout '+errors.slice(-2000))),10000);pending.set(mark,x=>{clearTimeout(timer);resolve(x);});child.stdin.write(JSON.stringify({mark})+'\n');}),close:async()=>{child.stdin.end(JSON.stringify({stop:true})+'\n');await new Promise((resolve,reject)=>{if(child.exitCode!==null)return child.exitCode===0?resolve():reject(Error('sampler exit '+child.exitCode+' '+errors.slice(-2000)));child.once('exit',c=>c===0?resolve():reject(Error('sampler exit '+c+' '+errors.slice(-2000))));});await new Promise(r=>log.end(r));}};
}
function dbStats(database){assert.match(database,/^qadb[a-f0-9]+$/);const sql="SELECT json_build_object('database_bytes',pg_database_size(current_database()),'wal_lsn_bytes',pg_wal_lsn_diff(pg_current_wal_lsn(),'0/0'),'sql_calls',(SELECT coalesce(sum(calls),0) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())),'sql_time_ms',(SELECT coalesce(sum(total_exec_time),0) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())),'heap_bytes',(SELECT coalesce(sum(pg_table_size(relid)),0) FROM pg_stat_user_tables),'index_bytes',(SELECT coalesce(sum(pg_indexes_size(relid)),0) FROM pg_stat_user_tables),'inserted_rows',(SELECT coalesce(sum(n_tup_ins),0) FROM pg_stat_user_tables),'updated_rows',(SELECT coalesce(sum(n_tup_upd),0) FROM pg_stat_user_tables),'deleted_rows',(SELECT coalesce(sum(n_tup_del),0) FROM pg_stat_user_tables),'sql_wal_bytes',(SELECT coalesce(sum(wal_bytes),0) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())),'temp_bytes',(SELECT temp_bytes FROM pg_stat_database WHERE datname=current_database()))";return JSON.parse(command('docker',['exec',container,'psql','-U','postgres','-d',database,'-At','-v','ON_ERROR_STOP=1','-c',sql]));}
function fileLedger(root){const groups={};let stack=[root];while(stack.length){const dir=stack.pop();for(const entry of fs.readdirSync(dir,{withFileTypes:true})){const p=path.join(dir,entry.name);if(entry.isSymbolicLink())continue;if(entry.isDirectory()){stack.push(p);continue;}if(!entry.isFile())continue;const group=path.relative(root,p).split(path.sep)[0],stat=fs.statSync(p);groups[group]??={files:0,logical_bytes:0,allocated_bytes:0};groups[group].files++;groups[group].logical_bytes+=stat.size;groups[group].allocated_bytes+=stat.blocks*512;}}return {groups,total_files:Object.values(groups).reduce((n,x)=>n+x.files,0),total_logical_bytes:Object.values(groups).reduce((n,x)=>n+x.logical_bytes,0),total_allocated_bytes:Object.values(groups).reduce((n,x)=>n+x.allocated_bytes,0),scope:'owned fixture cwd only; external archive roots and compaction backlog not inferred'};}
function pgNetwork(){const line=command('docker',['exec',container,'cat','/proc/net/dev']).split('\n').find(l=>l.trim().startsWith('eth0:'));assert.ok(line);const fields=line.split(':')[1].trim().split(/\s+/).map(Number);return {rx_bytes:fields[0],tx_bytes:fields[8]};}
const diff=(a,b)=>Object.fromEntries(Object.keys(b).map(k=>[k,b[k]-a[k]]));
function eventsCount(raw){return raw.split('\n').filter(l=>l.startsWith('data: ')).reduce((n,l)=>{try{return n+(JSON.parse(l.slice(6)).type==='response.output_text.delta'?1:0);}catch{return n;}},0);}
async function httpCall(url,options={}){
 const observation=options.probe_id?{probe_id:options.probe_id,input_text_sha256:textHash(options.body.input),start_ns:ns(),raw_data:[],delta_trace:[]}:null;
 const started=performance.now(),body=options.body?JSON.stringify(options.body):null;
 return new Promise(resolve=>{let finished=false;const finish=value=>{if(!finished){finished=true;if(observation)observation.result_ready_ns=ns();resolve({elapsed_ms:performance.now()-started,...value,...(observation?{observation}: {})});}};
 const req=http.request(url,{method:body?'POST':'GET',agent:false,headers:{...options.headers,...(body?{'content-type':'application/json','content-length':Buffer.byteLength(body)}:{})}},res=>{
  const headersMs=performance.now()-started;if(observation)observation.headers_ns=ns();const socket=res.socket,chunks=[];let ttft=null,partial='',lastDelta=null;const deltaGaps=[];
  res.on('data',c=>{const callback=observation?{receive_ns:ns(),bytes:c.length}:null;const callbackIndex=observation?.raw_data.length;if(callback)observation.raw_data.push(callback);try{chunks.push(c);if(options.stream){partial+=c.toString();let nl;while((nl=partial.indexOf('\n'))!==-1){const line=partial.slice(0,nl);partial=partial.slice(nl+1);if(!line.startsWith('data: '))continue;try{const event=JSON.parse(line.slice(6));if(event.type==='response.output_text.delta'){const now=performance.now();if(ttft===null)ttft=now-started;if(lastDelta!==null)deltaGaps.push(now-lastDelta);lastDelta=now;if(observation){const match=/^resource-probe-(\d{5})[|]$/.exec(event.delta);observation.delta_trace.push({delta_index:match?Number(match[1]):null,sequence_number:event.sequence_number,raw_callback_index:callbackIndex,parse_ns:ns()});}}if(event.type==='response.created'&&observation)observation.created_response_id=event.response?.id;if(event.type==='response.completed'&&observation)observation.protocol_terminal_ns=ns();}catch{}}}}finally{if(callback)callback.callback_exit_ns=ns();}});
  res.on('error',e=>finish({ok:false,error:e.message}));res.on('end',()=>{if(observation)observation.end_callback_ns=ns();const raw=Buffer.concat(chunks).toString();let result={headers_ms:headersMs,http:res.statusCode,bytes:Buffer.byteLength(raw),socket_tx_bytes:socket.bytesWritten,socket_rx_bytes:socket.bytesRead,ttft_ms:ttft,interdelta_gap_ms:deltaGaps,ok:res.statusCode===200};
   if(options.stream){const events=raw.split('\n').filter(l=>l.startsWith('data: ')).flatMap(l=>{try{return[JSON.parse(l.slice(6))]}catch{return[]}}),text=events.filter(e=>e.type==='response.output_text.delta').map(e=>e.delta).join('');result.completed=events.filter(e=>e.type==='response.completed').length;result.errors=events.filter(e=>['error','response.failed','response.incomplete','response.cancelled'].includes(e.type)).length;result.output_complete=text===fixedStream(options.output_observe).whole;result.output_sha256=crypto.createHash('sha256').update(text).digest('hex');result.response_id=events.find(e=>e.type==='response.created')?.response?.id;result.delta_count=eventsCount(raw);result.ok&&=result.completed===1&&result.errors===0&&result.output_complete&&ttft!==null&&result.delta_count===256;
   }else{try{result.body=JSON.parse(raw);}catch{result.ok=false;result.error='non-JSON response';}}if(!result.ok)result.error_body=raw.slice(0,4096);finish(result);
  });
 });req.setTimeout(90000,()=>req.destroy(Error('request timeout90000ms')));req.on('error',e=>finish({ok:false,error:e.message}));req.end(body);});
}
function statementSnapshot(database){const started=performance.now(),start_ns=ns();assert.match(database,/^qadb[a-f0-9]+$/);const sql="SELECT json_build_object('rows',coalesce(json_agg(json_build_object('queryid',queryid::text,'userid',userid::text,'toplevel',toplevel,'query',query,'calls',calls,'total_exec_time',total_exec_time,'rows',rows,'wal_bytes',wal_bytes)),'[]'::json),'info',(SELECT row_to_json(i) FROM pg_stat_statements_info i)) FROM pg_stat_statements WHERE dbid=(SELECT oid FROM pg_database WHERE datname=current_database())";const raw=execFileSync('docker',['exec',container,'psql','-U','postgres','-d',database,'-At','-v','ON_ERROR_STOP=1','-c',sql],{encoding:'utf8',maxBuffer:64*1024*1024});const data=JSON.parse(raw);data.rows=data.rows.map(({query,...row})=>{const normalized_sql=safeSql(query).replace(/\s+/g,' ').trim();return{...row,normalized_sql,query_fingerprint:crypto.createHash('sha256').update(normalized_sql).digest('hex')};});return{...data,start_ns,end_ns:ns(),observation_cost_ms:performance.now()-started,export_bytes:Buffer.byteLength(raw)};}
function nativeStats(database,appIds){assert.ok(appIds.every(x=>/^[a-f0-9-]{36}$/.test(x)));const ids=appIds.map(x=>`'${x}'::uuid`).join(',');const sql=`SELECT json_build_object('manifests',coalesce((SELECT json_agg(r) FROM (SELECT application_id::text, count(*)::bigint AS count, sum(byte_size)::bigint AS byte_size FROM runtime_native_snapshot_manifests WHERE application_id IN (${ids}) GROUP BY application_id) r),'[]'::json),'items',coalesce((SELECT json_agg(r) FROM (SELECT application_id::text,count(*)::bigint AS count,sum(byte_size)::bigint AS byte_size FROM runtime_native_snapshot_items WHERE application_id IN (${ids}) GROUP BY application_id) r),'[]'::json))`;const row=JSON.parse(command('docker',['exec',container,'psql','-U','postgres','-d',database,'-At','-v','ON_ERROR_STOP=1','-c',sql]));for(const group of ['manifests','items'])row[group]=row[group].map(({application_id,...x})=>({...x,app_alias:'app_'+appIds.indexOf(application_id)}));return row;}
async function fixture(label,kind,observe){
 const out=path.join(OUT,label);fs.mkdirSync(out,{recursive:true});let f,db,sampling,ownedCwd,loop,ownerClient;
 const mock=upstream(observe),sessions=[],result={label,kind,lane:observe?'observation':'performance',source:BASELINE,arm:kind==='baseline'?'same_app':'split_app',phases:[],cleanup:[],status:'fail',observer_costs:[]},secrets=[];
 const save=()=>fs.writeFileSync(path.join(out,'result.json'),redactServiceLog(JSON.stringify(result,null,2),secrets)+'\n');
 class Client extends OwnerHttpClient{constructor(...args){super(...args);ownerClient=this;}async signIn(account,password){const s=await openTemporaryOwnerSession({apiBaseUrl:this.baseUrl,account,password});sessions.push(s);this.attachSession(s.cookie,s.csrfToken);}}
 try{
  db=createDatabase({container,host:'127.0.0.1',port:5432});secrets.push(db.url,new URL(db.url).password);const database=new URL(db.url).pathname.slice(1);await mock.ready;
  f=await createGatewayFixture({databaseUrl:db.url,apiServerBin:binaries[kind],openaiPackage:packages.openai,anthropicPackage:packages.anthropic,openaiCompatiblePackage:packages.openai_compatible,upstreamBaseUrl:mock.url(),artifactRoot:path.join(out,'service')},{OwnerHttpClient:Client,spawnOwned:(bin,env,options)=>{ownedCwd=options.cwd;return spawnOwned(bin,{...env,FLOWBASE_PROVIDER_STREAM_TIMING_CAPTURE:'0'},options);}});
  const ready=f.result,target=ready.targets.openai,url=ready.gateway_base_url;assert.notEqual(new URL(url).port,'7600');for(const x of Object.values(ready.targets))secrets.push(x.api_key,x.durable.list_runs.headers.cookie);secrets.push(...sessions.map(s=>s.cookie));
  const cloneStarted=ns(),targets=[target];const initialDraft=await ownerClient.read(`/api/console/applications/${target.application_id}/orchestration`);const draftHash=crypto.createHash('sha256').update(semanticDraft(initialDraft.data.draft.document)).digest('hex');
  if(kind==='candidate')for(let i=1;i<8;i++){const provider={provider_code:'openai',provider_instance_id:target.provider_instance_id,installation_id:target.installation_id,model:target.upstream_model,package_sha256:ready.packages.openai.sha256};const app=await createPublishedApplication(ownerClient,provider,'1flowbase',i+1);const next=providerTarget(url,ownerClient,app);secrets.push(next.api_key);const draft=await ownerClient.read(`/api/console/applications/${next.application_id}/orchestration`);assert.equal(semanticDraft(draft.data.draft.document),semanticDraft(initialDraft.data.draft.document),'Equivalent app graph/config required');targets.push(next);}
  validateTargets(targets,result.arm);result.clone_setup={start_ns:cloneStarted,end_ns:ns(),applications:targets.length,provider_instances:new Set(targets.map(t=>t.provider_instance_id)).size,semantic_draft_sha256:draftHash};result.target_aliases=targets.map((_,i)=>'app_'+i);
  command('docker',['exec',container,'psql','-U','postgres','-d',database,'-c','CREATE EXTENSION IF NOT EXISTS pg_stat_statements']);result.packages=Object.fromEntries(Object.entries(ready.packages).map(([k,v])=>[k,v.sha256]));result.api_pid=f.gatewayPid;result.pg_pid=pgPid;
  if(observe){const before=BigInt(ns()),python=BigInt(command('python3',['-c','import time;print(time.monotonic_ns())'])),after=BigInt(ns());assert.ok(before<=python&&python<=after);const parent=clockIdentity(),source=mock.clock();for(const key of ['clock_id','time_namespace','node_version'])assert.equal(parent[key],source[key],'Independent mock clock identity '+key);assert.ok(BigInt(source.fork_start_ns)<=BigInt(source.monotonic_ns)&&BigInt(source.monotonic_ns)<=BigInt(source.ready_receive_ns),'Mock READY monotonic bracket');result.clock={...parent,source_receipt:source,max_clock_error_ns:(after-before).toString(),check:'Independent mock READY clock identity/time namespace/Node version; monotonic fork-to-ready bracket; Python CLOCK_MONOTONIC within Node bracket'};}
  await delay(30000);sampling=sampler(f.gatewayPid,mock.child.pid,out,database,targets.map(t=>t.application_id),secrets);await sampling.mark('whole:begin');if(observe){loop=loopProbe();result.eventloop_probe_interval_ms=loop.interval_ms;}
  const dbBefore=dbStats(database),netBefore=pgNetwork(),mockBefore=await mock.stats();result.files_before=fileLedger(ownedCwd);
  async function phase(name,work){
   console.log(JSON.stringify({label,lane:result.lane,phase:name,event:'start',at:new Date().toISOString()}));
   if(observe)await mock.setPhase(name);
   const statementBefore=observe?statementSnapshot(database):null;if(statementBefore)result.observer_costs.push({phase:name,where:'before',ms:statementBefore.observation_cost_ms,export_bytes:statementBefore.export_bytes});
   const begin=await sampling.mark(name+':begin'),databaseBefore=dbStats(database),networkBefore=pgNetwork(),upstreamBefore=await mock.stats(),record={name,requests:[],observer_enabled:observe};result.phases.push(record);
   if(observe){record.begin_ns=ns();loop.resume();}
   try{await work(record);}catch(e){record.error=e.message;record.failed=true;}
   if(observe){record.end_work_ns=ns();loop.pause();}
   const end=await sampling.mark(name+':end'),slice=sampling.samples.filter(s=>s.monotonic_ns>=begin.monotonic_ns&&s.monotonic_ns<=end.monotonic_ns);
   record.resources=summarize(slice,ticks,record.requests.length);if(name==='fixedstream_h524288_c8'){record.lock_observation_samples=sampling.lockSamples.filter(r=>r.phase===name);record.lock_observer_errors=[...sampling.lockErrors];record.lock_observer_guard={samples:record.lock_observation_samples.length,errors:record.lock_observer_errors.length,require_at_least:2};if(record.lock_observation_samples.length<2||record.lock_observer_errors.length)record.failed=true;record.postgres_observer_resources=summarize(slice.map(s=>({...s,processes:s.processes.filter(p=>p.postgres_observer_backend)})),ticks,0).groups.postgres;}record.resource_guard={memory_used_peak:Math.max(...slice.map(s=>1-s.memory_available_bytes/s.memory_total_bytes)),disk_used_peak:Math.max(...slice.map(s=>1-s.disk_available_bytes/s.disk_total_bytes)),limit:.9};if(record.resource_guard.memory_used_peak>.9||record.resource_guard.disk_used_peak>.9)record.failed=true;
   record.request_summary=requestSummary(record.requests,record.resources.wall_seconds);record.stream_summary=requestSummary(record.requests.filter(r=>['gateway_stream','direct_stream'].includes(r.request_class)),record.resources.wall_seconds);
   record.database_delta=diff(databaseBefore,dbStats(database));record.postgres_network_delta=diff(networkBefore,pgNetwork());const after=await mock.stats();record.upstream_delta=diff(Object.fromEntries(Object.entries(upstreamBefore).filter(([,v])=>typeof v==='number')),Object.fromEntries(Object.entries(after).filter(([,v])=>typeof v==='number')));
   if(observe){const statementAfter=statementSnapshot(database);result.observer_costs.push({phase:name,where:'after',ms:statementAfter.observation_cost_ms,export_bytes:statementAfter.export_bytes});record.pg_statement_snapshots={before:statementBefore,after:statementAfter};record.pg_statement_delta=sqlDelta(statementBefore.rows,statementAfter.rows);record.pg_statement_guard=sqlGuard(statementBefore.info,statementAfter.info,record.pg_statement_delta);if(!record.pg_statement_guard.valid){record.statement_counter_guard='reset/eviction/missing; SQL completeness unavailable, retain raw CPU/gap';}
    const streams=record.requests.filter(r=>r.observation);if(streams.length){try{record.matched_boundary_observation=correlate(streams,after.request_timeline,name,result.clock);for(const receipt of record.matched_boundary_observation){const client=streams.find(r=>r.observation.probe_id===receipt.probe_id);client.observation_trace=receipt;}}catch(e){record.failed=true;record.correlation_error=e.message;}}
   }
   save();console.log(JSON.stringify({label,phase:name,event:'end',attempted:record.requests.length,failed:record.requests.filter(r=>!r.ok).length,guard_failed:Boolean(record.failed)}));if(record.failed||record.requests.some(r=>!r.ok))throw Error('phase guard '+name);
  }
  await phase('idle',async()=>delay(10000));
  result.native_before_warm=nativeStats(database,targets.map(t=>t.application_id));result.warmups=[];
  for(let i=0;i<8;i++){const t=targets[kind==='candidate'?i:0];const warm=await httpCall(t.gateway.responses_url,{headers:{authorization:t.gateway.authorization},body:{model:'1flowbase',stream:true,input:history(524288)},stream:true,output_observe:true});assert.ok(warm.ok,'warmup completeness');result.warmups.push({...warm,excluded:true,app_alias:kind==='candidate'?'app_'+i:'app_0'});const native=await nativeObservation({...warm,target_index:kind==='candidate'?i:0});assert.equal(native.native_status,'succeeded','warm native terminal observation');}
  result.native_after_warm=nativeStats(database,targets.map(t=>t.application_id));await delay(30000);const runs=[];
  async function nativeObservation(row){assert.match(row.response_id,/^resp_/);const started=ns(),nativeTarget=targets[row.target_index||0];const native=await httpCall(nativeTarget.durable.query_run.url_template.replace('{run_id}',row.response_id.slice(5)),{headers:nativeTarget.durable.query_run.headers});const data=native.body?.data||native.body;const status=data?.status||data?.run?.status;delete native.body;return{...native,request_class:'native_status',run_id:row.response_id.slice(5),native_status:status,start_ns:started,end_ns:ns(),boundary:'native status observed via query; not exact commit/flush/billing time'};}
  const level=8,rounds=1;
  async function batch(mode,record){const rows=await Promise.all(Array.from({length:8},(_,i)=>{const key='scope:h524288:c8:r0:i'+i,input=observedHistory(524288,key),t=targets[kind==='candidate'?i:0];return httpCall(mode==='gateway'?t.gateway.responses_url:mock.url()+'/v1/responses',{headers:mode==='gateway'?{authorization:t.gateway.authorization}:undefined,body:{model:mode==='gateway'?'1flowbase':t.upstream_model,stream:true,input},stream:true,output_observe:true,probe_id:key}).then(x=>({...x,target_index:kind==='candidate'?i:0,app_alias:kind==='candidate'?'app_'+i:'app_0'}));}));record.requests.push(...rows.map(x=>({...x,round:0,request_class:mode==='gateway'?'gateway_stream':'direct_stream'})));if(rows.some(x=>!x.ok))throw Error(mode+' output completeness');if(mode==='gateway'){distinctRuns(rows);runs.push(...rows);record.distinct_native_runs=8;}await delay(1000);}
  await phase('direct_before_h524288_c8',r=>batch('direct',r));result.native_before_measured=nativeStats(database,targets.map(t=>t.application_id));await phase('fixedstream_h524288_c8',r=>batch('gateway',r));result.native_after_measured=nativeStats(database,targets.map(t=>t.application_id));await phase('direct_after_h524288_c8',r=>batch('direct',r));
  await phase('drain_observation',async r=>{for(const row of runs){let terminal=false;for(let retry=0;retry<20;retry++){const native=await nativeObservation(row);r.requests.push(native);if(native.native_status==='succeeded'){terminal=true;break;}await delay(250);}assert.ok(terminal,'native durable terminal status');}for(let retry=0;(await mock.stats()).active&&retry<40;retry++)await delay(250);assert.equal((await mock.stats()).active,0);await delay(5000);result.drain={native_runs:runs.length,mock_active:0,quiescence_observation_seconds:5,protocol_flush_receipt:'not exposed/unverified; no total-backlog or storage-saving claim',native_receipt:'status succeeded observed; Native/protocol exact persist and billing times not captured'};});
  const end=await sampling.mark('whole:end');result.total=summarize(sampling.samples.filter(s=>s.monotonic_ns<=end.monotonic_ns),ticks,0);result.total.accounting={scope:'whole fixture including8 sequential warmups, warmup Native queries, warm settle, idle and SQL snapshot export; no per-request denominator',measured_http_requests:result.phases.reduce((n,p)=>n+p.requests.length,0),excluded_warmup_stream_requests:8,excluded_warmup_native_requests:8};result.total.database_delta=diff(dbBefore,dbStats(database));result.files_after=fileLedger(ownedCwd);result.owned_cwd_storage_growth={files:result.files_after.total_files-result.files_before.total_files,logical_bytes:result.files_after.total_logical_bytes-result.files_before.total_logical_bytes,allocated_bytes:result.files_after.total_allocated_bytes-result.files_before.total_allocated_bytes};result.total.postgres_network_delta=diff(netBefore,pgNetwork());const mockAfter=await mock.stats();result.total.upstream_delta=diff(Object.fromEntries(Object.entries(mockBefore).filter(([,v])=>typeof v==='number')),Object.fromEntries(Object.entries(mockAfter).filter(([,v])=>typeof v==='number')));result.actual_mock_interdelta_gap_ms=mockAfter.interdelta_gap_ms;result.mock_request_timeline=mockAfter.request_timeline;assert.ok(mockAfter.request_timeline.every(r=>r.input_items===128&&r.input_text_bytes===524288));result.status='pass';
 }catch(e){result.error=redactServiceLog(e.message,secrets);}finally{
  if(loop){loop.stop();result.eventloop_lag=loop.rows;result.eventloop_probe_excluded_intervals=loop.excluded;}if(sampling)try{await sampling.close();result.lock_observer_summary=sampling.summary();}catch(e){result.cleanup.push('sampler-failed');result.sampler_error=redactServiceLog(e.message,secrets);result.error??=result.sampler_error;result.status='fail';}
  for(const s of sessions)try{await s.dispose();result.cleanup.push('session-disposed');}catch{result.status='fail';result.cleanup.push('session-dispose-failed');}
  for(const [name,close]of [['fixture',()=>f?.close()],['mock',()=>mock.close()],['database',()=>db?.close()]])try{await close();result.cleanup.push(name+'-closed');}catch{result.status='fail';result.cleanup.push(name+'-cleanup-failed');}save();
 }
 return result;
}
(async()=>{const results=[];const observe=true;for(const [part,kind]of [['A1','baseline'],['B1','candidate'],['B2','candidate'],['A2','baseline']]){const label=part;const r=await fixture(label,kind,observe);results.push(r);console.log(JSON.stringify({label,status:r.status,error:r.error}));if(r.status!=='pass'){fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify({manifest,results,complete:false},null,2));process.exitCode=1;return;}}fs.writeFileSync(path.join(OUT,'summary.json'),JSON.stringify({manifest,results,complete:true},null,2));})().catch(e=>{console.error(e.message);process.exitCode=1;});
